package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import java.util.concurrent.Flow;
import org.jspecify.annotations.Nullable;

/** Named contract operations for the agents service. Generated by scripts/generate_endpoints.py. */
public class AgentsServiceClient extends ServiceClient {
    AgentsServiceClient(ApiClient client) {
        super(ApiService.AGENTS, client);
    }

    /**
     * Calls the contract route {@code DELETE /agents/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("agents|DELETE|/agents/{param}")
    public <T> @Nullable T deleteAgentsParam(String pathParam1, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Agents.DELETE_AGENTS_PARAM, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code DELETE /agents/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T deleteAgentsParam(String pathParam1, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Agents.DELETE_AGENTS_PARAM, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /agents}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("agents|GET|/agents")
    public <T> @Nullable T getAgents(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Agents.GET_AGENTS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /agents}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getAgents(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Agents.GET_AGENTS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /agents/health}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("agents|GET|/agents/health")
    public <T> @Nullable T getAgentsHealth(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Agents.GET_AGENTS_HEALTH, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /agents/health}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getAgentsHealth(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Agents.GET_AGENTS_HEALTH, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /agents/runs/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("agents|GET|/agents/runs/{param}")
    public <T> @Nullable T getAgentsRunsParam(String pathParam1, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Agents.GET_AGENTS_RUNS_PARAM, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /agents/runs/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getAgentsRunsParam(String pathParam1, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Agents.GET_AGENTS_RUNS_PARAM, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /agents/runs/{param}/conversation}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("agents|GET|/agents/runs/{param}/conversation")
    public <T> @Nullable T getAgentsRunsParamConversation(String pathParam1, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Agents.GET_AGENTS_RUNS_PARAM_CONVERSATION, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /agents/runs/{param}/conversation}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getAgentsRunsParamConversation(
            String pathParam1, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Agents.GET_AGENTS_RUNS_PARAM_CONVERSATION, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /agents/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("agents|GET|/agents/{param}")
    public <T> @Nullable T getAgentsParam(String pathParam1, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Agents.GET_AGENTS_PARAM, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /agents/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getAgentsParam(String pathParam1, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Agents.GET_AGENTS_PARAM, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /agents/{param}/runs}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("agents|GET|/agents/{param}/runs")
    public <T> @Nullable T getAgentsParamRuns(String pathParam1, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Agents.GET_AGENTS_PARAM_RUNS, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /agents/{param}/runs}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getAgentsParamRuns(String pathParam1, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Agents.GET_AGENTS_PARAM_RUNS, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /agents/{param}/versions}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("agents|GET|/agents/{param}/versions")
    public <T> @Nullable T getAgentsParamVersions(String pathParam1, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Agents.GET_AGENTS_PARAM_VERSIONS, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /agents/{param}/versions}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getAgentsParamVersions(String pathParam1, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Agents.GET_AGENTS_PARAM_VERSIONS, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code POST /agents}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("agents|POST|/agents")
    public <T> @Nullable T postAgents(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Agents.POST_AGENTS, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /agents}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postAgents(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Agents.POST_AGENTS, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /agents/{param}/rollback}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("agents|POST|/agents/{param}/rollback")
    public <T> @Nullable T postAgentsParamRollback(
            String pathParam1, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Agents.POST_AGENTS_PARAM_ROLLBACK, List.of(pathParam1), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /agents/{param}/rollback}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postAgentsParamRollback(
            String pathParam1, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Agents.POST_AGENTS_PARAM_ROLLBACK, List.of(pathParam1), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /agents/{param}/runs}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("agents|POST|/agents/{param}/runs")
    public <T> @Nullable T postAgentsParamRuns(
            String pathParam1, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Agents.POST_AGENTS_PARAM_RUNS, List.of(pathParam1), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /agents/{param}/runs}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postAgentsParamRuns(
            String pathParam1, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Agents.POST_AGENTS_PARAM_RUNS, List.of(pathParam1), query, body, responseType);
    }

    /**
     * Calls the contract route {@code PUT /agents/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("agents|PUT|/agents/{param}")
    public <T> @Nullable T putAgentsParam(
            String pathParam1, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Agents.PUT_AGENTS_PARAM, List.of(pathParam1), query, body, responseType);
    }

    /**
     * Calls the contract route {@code PUT /agents/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T putAgentsParam(
            String pathParam1, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Agents.PUT_AGENTS_PARAM, List.of(pathParam1), query, body, responseType);
    }

    /**
     * Opens the event stream for {@code STREAM /agents/runs/{param}/stream}.
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @return a publisher that emits event data
     */
    @SdkOperation("agents|STREAM|/agents/runs/{param}/stream")
    public Flow.Publisher<String> streamAgentsRunsParamStream(String pathParam1, QueryParams query) {
        return streamPublisher(Endpoints.Agents.STREAM_AGENTS_RUNS_PARAM_STREAM, List.of(pathParam1), query);
    }

    /**
     * Opens a blocking event stream for {@code STREAM /agents/runs/{param}/stream}.
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @return an iterator that must be closed
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public SseEventIterator streamAgentsRunsParamStreamBlocking(String pathParam1, QueryParams query)
            throws IOException, InterruptedException {
        return streamEvents(Endpoints.Agents.STREAM_AGENTS_RUNS_PARAM_STREAM, List.of(pathParam1), query);
    }
}
