package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for agents/versions. Generated by scripts/generate_endpoints.py. */
public final class AgentsVersionsClient extends ServiceClient {
    AgentsVersionsClient(ApiClient client) {
        super(ApiService.AGENTS, client);
    }

    /**
     * Calls the contract route {@code GET /agents/{param}/versions}.
     * @param <T> decoded response type
     * @param agentId agentId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("agents|GET|/agents/{param}/versions")
    public <T> @Nullable T list(String agentId, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Agents.GET_AGENTS_PARAM_VERSIONS, List.of(agentId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /agents/{param}/versions} using a generic response type.
     * @param <T> decoded response type
     * @param agentId agentId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(String agentId, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Agents.GET_AGENTS_PARAM_VERSIONS, List.of(agentId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /agents/{param}/versions} without query parameters.
     * @param <T> decoded response type
     * @param agentId agentId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(String agentId, Class<T> responseType) throws IOException, InterruptedException {
        return list(agentId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /agents/{param}/versions} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param agentId agentId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(String agentId, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return list(agentId, QueryParams.empty(), responseType);
    }
}
