package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import org.jspecify.annotations.Nullable;

/** Contract operations for ai/internal. Generated by scripts/generate_endpoints.py. */
public final class AiInternalClient extends ServiceClient {
    AiInternalClient(ApiClient client) {
        super(ApiService.AI, client);
    }

    /** Returns the client for the nested resource.
     * @return the models resource client
     */
    public AiInternalModelsClient models() {
        return new AiInternalModelsClient(client());
    }

    /**
     * Calls the contract route {@code POST /internal/embeddings}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ai|POST|/internal/embeddings")
    public <T> @Nullable T embed(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ai.POST_INTERNAL_EMBEDDINGS, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /internal/embeddings} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T embed(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ai.POST_INTERNAL_EMBEDDINGS, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /internal/embeddings} without query parameters.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T embed(@Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return embed(QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /internal/embeddings} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T embed(@Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return embed(QueryParams.empty(), body, responseType);
    }

    /**
     * Calls the contract route {@code POST /internal/predictions}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ai|POST|/internal/predictions")
    public <T> @Nullable T predict(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ai.POST_INTERNAL_PREDICTIONS, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /internal/predictions} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T predict(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ai.POST_INTERNAL_PREDICTIONS, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /internal/predictions} without query parameters.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T predict(@Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return predict(QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /internal/predictions} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T predict(@Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return predict(QueryParams.empty(), body, responseType);
    }

    /**
     * Calls the contract route {@code POST /internal/rerank}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ai|POST|/internal/rerank")
    public <T> @Nullable T rerank(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ai.POST_INTERNAL_RERANK, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /internal/rerank} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T rerank(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ai.POST_INTERNAL_RERANK, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /internal/rerank} without query parameters.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T rerank(@Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return rerank(QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /internal/rerank} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T rerank(@Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return rerank(QueryParams.empty(), body, responseType);
    }

    /**
     * Calls the contract route {@code POSTFORMDATA /internal/predictions}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param fields fields supplied to the operation
     * @param files files supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ai|POSTFORMDATA|/internal/predictions")
    public <T> @Nullable T predictForm(
            QueryParams query, Map<String, String> fields, Map<String, Path> files, Class<T> responseType)
            throws IOException, InterruptedException {
        return requestForm(
                Endpoints.Ai.POSTFORMDATA_INTERNAL_PREDICTIONS, List.of(), query, fields, files, responseType);
    }
    /**
     * Calls the contract route {@code POSTFORMDATA /internal/predictions} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param fields fields supplied to the operation
     * @param files files supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T predictForm(
            QueryParams query, Map<String, String> fields, Map<String, Path> files, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return requestForm(
                Endpoints.Ai.POSTFORMDATA_INTERNAL_PREDICTIONS, List.of(), query, fields, files, responseType);
    }
    /**
     * Calls the contract route {@code POSTFORMDATA /internal/predictions} without query parameters.
     * @param <T> decoded response type
     * @param fields fields supplied to the operation
     * @param files files supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T predictForm(Map<String, String> fields, Map<String, Path> files, Class<T> responseType)
            throws IOException, InterruptedException {
        return predictForm(QueryParams.empty(), fields, files, responseType);
    }
    /**
     * Calls the contract route {@code POSTFORMDATA /internal/predictions} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param fields fields supplied to the operation
     * @param files files supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T predictForm(
            Map<String, String> fields, Map<String, Path> files, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return predictForm(QueryParams.empty(), fields, files, responseType);
    }

    /**
     * Calls the contract route {@code POSTRAW /internal/predictions}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ai|POSTRAW|/internal/predictions")
    public <T> @Nullable T predictRaw(QueryParams query, byte[] body, Class<T> responseType)
            throws IOException, InterruptedException {
        return requestRaw(Endpoints.Ai.POSTRAW_INTERNAL_PREDICTIONS, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POSTRAW /internal/predictions} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T predictRaw(QueryParams query, byte[] body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return requestRaw(Endpoints.Ai.POSTRAW_INTERNAL_PREDICTIONS, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POSTRAW /internal/predictions} without query parameters.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T predictRaw(byte[] body, Class<T> responseType) throws IOException, InterruptedException {
        return predictRaw(QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POSTRAW /internal/predictions} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T predictRaw(byte[] body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return predictRaw(QueryParams.empty(), body, responseType);
    }
}
