package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import org.jspecify.annotations.Nullable;

/** Named contract operations for the ai service. Generated by scripts/generate_endpoints.py. */
public class AiServiceClient extends ServiceClient {
    AiServiceClient(ApiClient client) {
        super(ApiService.AI, client);
    }

    /**
     * Calls the contract route {@code GET /health}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ai|GET|/health")
    public <T> @Nullable T getHealth(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ai.GET_HEALTH, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /health}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getHealth(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ai.GET_HEALTH, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /internal/models}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ai|GET|/internal/models")
    public <T> @Nullable T getInternalModels(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ai.GET_INTERNAL_MODELS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /internal/models}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getInternalModels(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ai.GET_INTERNAL_MODELS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /internal/models/defaults}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ai|GET|/internal/models/defaults")
    public <T> @Nullable T getInternalModelsDefaults(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ai.GET_INTERNAL_MODELS_DEFAULTS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /internal/models/defaults}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getInternalModelsDefaults(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ai.GET_INTERNAL_MODELS_DEFAULTS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code POST /ai/chat/completions}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ai|POST|/ai/chat/completions")
    public <T> @Nullable T postAiChatCompletions(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ai.POST_AI_CHAT_COMPLETIONS, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /ai/chat/completions}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postAiChatCompletions(
            QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ai.POST_AI_CHAT_COMPLETIONS, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /internal/embeddings}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ai|POST|/internal/embeddings")
    public <T> @Nullable T postInternalEmbeddings(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ai.POST_INTERNAL_EMBEDDINGS, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /internal/embeddings}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postInternalEmbeddings(
            QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ai.POST_INTERNAL_EMBEDDINGS, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /internal/predictions}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ai|POST|/internal/predictions")
    public <T> @Nullable T postInternalPredictions(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ai.POST_INTERNAL_PREDICTIONS, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /internal/predictions}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postInternalPredictions(
            QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ai.POST_INTERNAL_PREDICTIONS, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /internal/rerank}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ai|POST|/internal/rerank")
    public <T> @Nullable T postInternalRerank(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ai.POST_INTERNAL_RERANK, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /internal/rerank}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postInternalRerank(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ai.POST_INTERNAL_RERANK, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POSTFORMDATA /internal/predictions}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param fields fields supplied to the operation
     * @param files files supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ai|POSTFORMDATA|/internal/predictions")
    public <T> @Nullable T postformdataInternalPredictions(
            QueryParams query, Map<String, String> fields, Map<String, Path> files, Class<T> responseType)
            throws IOException, InterruptedException {
        return requestForm(
                Endpoints.Ai.POSTFORMDATA_INTERNAL_PREDICTIONS, List.of(), query, fields, files, responseType);
    }

    /**
     * Calls the contract route {@code POSTFORMDATA /internal/predictions}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param fields fields supplied to the operation
     * @param files files supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postformdataInternalPredictions(
            QueryParams query, Map<String, String> fields, Map<String, Path> files, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return requestForm(
                Endpoints.Ai.POSTFORMDATA_INTERNAL_PREDICTIONS, List.of(), query, fields, files, responseType);
    }

    /**
     * Calls the contract route {@code POSTRAW /internal/predictions}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ai|POSTRAW|/internal/predictions")
    public <T> @Nullable T postrawInternalPredictions(QueryParams query, byte[] body, Class<T> responseType)
            throws IOException, InterruptedException {
        return requestRaw(Endpoints.Ai.POSTRAW_INTERNAL_PREDICTIONS, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POSTRAW /internal/predictions}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postrawInternalPredictions(QueryParams query, byte[] body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return requestRaw(Endpoints.Ai.POSTRAW_INTERNAL_PREDICTIONS, List.of(), query, body, responseType);
    }
}
