package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for audit. Generated by scripts/generate_endpoints.py. */
public final class AuditClient extends ServiceClient {
    AuditClient(ApiClient client) {
        super(ApiService.AUDIT, client);
    }

    /** Returns the client for the nested resource.
     * @return the events resource client
     */
    public AuditEventsClient events() {
        return new AuditEventsClient(client());
    }

}
