package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Named contract operations for the audit service. Generated by scripts/generate_endpoints.py. */
public final class AuditClient extends ServiceClient {
    AuditClient(ApiClient client) {
        super(ApiService.AUDIT, client);
    }

    /**
     * Calls the contract route {@code GET /audit/events}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("audit|GET|/audit/events")
    public <T> @Nullable T getAuditEvents(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Audit.GET_AUDIT_EVENTS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /audit/events}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getAuditEvents(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Audit.GET_AUDIT_EVENTS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /audit/events/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("audit|GET|/audit/events/{param}")
    public <T> @Nullable T getAuditEventsParam(String pathParam1, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Audit.GET_AUDIT_EVENTS_PARAM, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /audit/events/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getAuditEventsParam(String pathParam1, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Audit.GET_AUDIT_EVENTS_PARAM, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code POST /audit/events}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("audit|POST|/audit/events")
    public <T> @Nullable T postAuditEvents(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Audit.POST_AUDIT_EVENTS, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /audit/events}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postAuditEvents(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Audit.POST_AUDIT_EVENTS, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /audit/events/batch}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("audit|POST|/audit/events/batch")
    public <T> @Nullable T postAuditEventsBatch(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Audit.POST_AUDIT_EVENTS_BATCH, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /audit/events/batch}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postAuditEventsBatch(
            QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Audit.POST_AUDIT_EVENTS_BATCH, List.of(), query, body, responseType);
    }
}
