package dev.frontal.sdk;

/** Contract operations for audit. Generated by scripts/generate_endpoints.py. */
public final class AuditClient extends ServiceClient {
    AuditClient(ApiClient client) {
        super(ApiService.AUDIT, client);
    }

    /** Returns the client for the nested resource.
     * @return the events resource client
     */
    public AuditEventsClient events() {
        return new AuditEventsClient(client());
    }
}
