package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for billing/invoices. Generated by scripts/generate_endpoints.py. */
public final class BillingInvoicesClient extends ServiceClient {
    BillingInvoicesClient(ApiClient client) {
        super(ApiService.BILLING, client);
    }

    /**
     * Calls the contract route {@code GETRAW /billing/invoices/{param}/pdf}.
     * @param <T> decoded response type
     * @param invoiceId invoiceId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("billing|GETRAW|/billing/invoices/{param}/pdf")
    public <T> @Nullable T getPdf(String invoiceId, QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Billing.GETRAW_BILLING_INVOICES_PARAM_PDF, List.of(invoiceId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GETRAW /billing/invoices/{param}/pdf} using a generic response type.
     * @param <T> decoded response type
     * @param invoiceId invoiceId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getPdf(String invoiceId, QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Billing.GETRAW_BILLING_INVOICES_PARAM_PDF, List.of(invoiceId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GETRAW /billing/invoices/{param}/pdf} without query parameters.
     * @param <T> decoded response type
     * @param invoiceId invoiceId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getPdf(String invoiceId, Class<T> responseType) throws IOException, InterruptedException {
        return getPdf(invoiceId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GETRAW /billing/invoices/{param}/pdf} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param invoiceId invoiceId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getPdf(String invoiceId, TypeReference<T> responseType) throws IOException, InterruptedException {
        return getPdf(invoiceId, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code POST /billing/invoices/preview}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("billing|POST|/billing/invoices/preview")
    public <T> @Nullable T preview(QueryParams query, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Billing.POST_BILLING_INVOICES_PREVIEW, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /billing/invoices/preview} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T preview(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Billing.POST_BILLING_INVOICES_PREVIEW, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /billing/invoices/preview} without query parameters.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T preview(@Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return preview(QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /billing/invoices/preview} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T preview(@Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return preview(QueryParams.empty(), body, responseType);
    }

    /**
     * Calls the contract route {@code POST /billing/invoices/{param}/finalize}.
     * @param <T> decoded response type
     * @param invoiceId invoiceId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("billing|POST|/billing/invoices/{param}/finalize")
    public <T> @Nullable T finalize(String invoiceId, QueryParams query, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Billing.POST_BILLING_INVOICES_PARAM_FINALIZE, List.of(invoiceId), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /billing/invoices/{param}/finalize} using a generic response type.
     * @param <T> decoded response type
     * @param invoiceId invoiceId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T finalize(String invoiceId, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Billing.POST_BILLING_INVOICES_PARAM_FINALIZE, List.of(invoiceId), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /billing/invoices/{param}/finalize} without query parameters.
     * @param <T> decoded response type
     * @param invoiceId invoiceId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T finalize(String invoiceId, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return finalize(invoiceId, QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /billing/invoices/{param}/finalize} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param invoiceId invoiceId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T finalize(String invoiceId, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return finalize(invoiceId, QueryParams.empty(), body, responseType);
    }

    /**
     * Calls the contract route {@code POST /billing/invoices/{param}/void}.
     * @param <T> decoded response type
     * @param invoiceId invoiceId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("billing|POST|/billing/invoices/{param}/void")
    public <T> @Nullable T resourceVoid(String invoiceId, QueryParams query, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Billing.POST_BILLING_INVOICES_PARAM_VOID, List.of(invoiceId), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /billing/invoices/{param}/void} using a generic response type.
     * @param <T> decoded response type
     * @param invoiceId invoiceId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T resourceVoid(String invoiceId, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Billing.POST_BILLING_INVOICES_PARAM_VOID, List.of(invoiceId), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /billing/invoices/{param}/void} without query parameters.
     * @param <T> decoded response type
     * @param invoiceId invoiceId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T resourceVoid(String invoiceId, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return resourceVoid(invoiceId, QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /billing/invoices/{param}/void} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param invoiceId invoiceId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T resourceVoid(String invoiceId, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return resourceVoid(invoiceId, QueryParams.empty(), body, responseType);
    }

}
