package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import org.jspecify.annotations.Nullable;

/** Named contract operations for the blob service. Generated by scripts/generate_endpoints.py. */
public final class BlobClient extends ServiceClient {
    BlobClient(ApiClient client) {
        super(ApiService.BLOB, client);
    }

    /**
     * Calls the contract route {@code DELETE /blob/object/{param}/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param pathParam2 pathParam2 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("blob|DELETE|/blob/object/{param}/{param}")
    public <T> @Nullable T deleteBlobObjectParamParam(
            String pathParam1, String pathParam2, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Blob.DELETE_BLOB_OBJECT_PARAM_PARAM,
                List.of(pathParam1, pathParam2),
                query,
                null,
                responseType);
    }

    /**
     * Calls the contract route {@code DELETE /blob/object/{param}/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param pathParam2 pathParam2 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T deleteBlobObjectParamParam(
            String pathParam1, String pathParam2, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Blob.DELETE_BLOB_OBJECT_PARAM_PARAM,
                List.of(pathParam1, pathParam2),
                query,
                null,
                responseType);
    }

    /**
     * Calls the contract route {@code GET /blob/object/info/{param}/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param pathParam2 pathParam2 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("blob|GET|/blob/object/info/{param}/{param}")
    public <T> @Nullable T getBlobObjectInfoParamParam(
            String pathParam1, String pathParam2, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Blob.GET_BLOB_OBJECT_INFO_PARAM_PARAM,
                List.of(pathParam1, pathParam2),
                query,
                null,
                responseType);
    }

    /**
     * Calls the contract route {@code GET /blob/object/info/{param}/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param pathParam2 pathParam2 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getBlobObjectInfoParamParam(
            String pathParam1, String pathParam2, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Blob.GET_BLOB_OBJECT_INFO_PARAM_PARAM,
                List.of(pathParam1, pathParam2),
                query,
                null,
                responseType);
    }

    /**
     * Calls the contract route {@code GET /blob/object/{param}/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param pathParam2 pathParam2 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("blob|GET|/blob/object/{param}/{param}")
    public <T> @Nullable T getBlobObjectParamParam(
            String pathParam1, String pathParam2, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Blob.GET_BLOB_OBJECT_PARAM_PARAM, List.of(pathParam1, pathParam2), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /blob/object/{param}/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param pathParam2 pathParam2 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getBlobObjectParamParam(
            String pathParam1, String pathParam2, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Blob.GET_BLOB_OBJECT_PARAM_PARAM, List.of(pathParam1, pathParam2), query, null, responseType);
    }

    /**
     * Calls the contract route {@code POST /blob/object/copy}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("blob|POST|/blob/object/copy")
    public <T> @Nullable T postBlobObjectCopy(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Blob.POST_BLOB_OBJECT_COPY, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /blob/object/copy}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postBlobObjectCopy(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Blob.POST_BLOB_OBJECT_COPY, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /blob/object/list/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("blob|POST|/blob/object/list/{param}")
    public <T> @Nullable T postBlobObjectListParam(
            String pathParam1, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Blob.POST_BLOB_OBJECT_LIST_PARAM, List.of(pathParam1), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /blob/object/list/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postBlobObjectListParam(
            String pathParam1, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Blob.POST_BLOB_OBJECT_LIST_PARAM, List.of(pathParam1), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /blob/object/move}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("blob|POST|/blob/object/move")
    public <T> @Nullable T postBlobObjectMove(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Blob.POST_BLOB_OBJECT_MOVE, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /blob/object/move}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postBlobObjectMove(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Blob.POST_BLOB_OBJECT_MOVE, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /blob/object/sign/{param}/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param pathParam2 pathParam2 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("blob|POST|/blob/object/sign/{param}/{param}")
    public <T> @Nullable T postBlobObjectSignParamParam(
            String pathParam1, String pathParam2, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Blob.POST_BLOB_OBJECT_SIGN_PARAM_PARAM,
                List.of(pathParam1, pathParam2),
                query,
                body,
                responseType);
    }

    /**
     * Calls the contract route {@code POST /blob/object/sign/{param}/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param pathParam2 pathParam2 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postBlobObjectSignParamParam(
            String pathParam1,
            String pathParam2,
            QueryParams query,
            @Nullable JsonNode body,
            TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Blob.POST_BLOB_OBJECT_SIGN_PARAM_PARAM,
                List.of(pathParam1, pathParam2),
                query,
                body,
                responseType);
    }

    /**
     * Calls the contract route {@code POSTFORMDATA /blob/object/{param}/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param pathParam2 pathParam2 supplied to the operation
     * @param query query supplied to the operation
     * @param fields fields supplied to the operation
     * @param files files supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("blob|POSTFORMDATA|/blob/object/{param}/{param}")
    public <T> @Nullable T postformdataBlobObjectParamParam(
            String pathParam1,
            String pathParam2,
            QueryParams query,
            Map<String, String> fields,
            Map<String, Path> files,
            Class<T> responseType)
            throws IOException, InterruptedException {
        return requestForm(
                Endpoints.Blob.POSTFORMDATA_BLOB_OBJECT_PARAM_PARAM,
                List.of(pathParam1, pathParam2),
                query,
                fields,
                files,
                responseType);
    }

    /**
     * Calls the contract route {@code POSTFORMDATA /blob/object/{param}/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param pathParam2 pathParam2 supplied to the operation
     * @param query query supplied to the operation
     * @param fields fields supplied to the operation
     * @param files files supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postformdataBlobObjectParamParam(
            String pathParam1,
            String pathParam2,
            QueryParams query,
            Map<String, String> fields,
            Map<String, Path> files,
            TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return requestForm(
                Endpoints.Blob.POSTFORMDATA_BLOB_OBJECT_PARAM_PARAM,
                List.of(pathParam1, pathParam2),
                query,
                fields,
                files,
                responseType);
    }
}
