package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for blob/object/list. Generated by scripts/generate_endpoints.py. */
public final class BlobObjectListClient extends ServiceClient {
    BlobObjectListClient(ApiClient client) {
        super(ApiService.BLOB, client);
    }

    /**
     * Calls the contract route {@code POST /blob/object/list/{param}}.
     * @param <T> decoded response type
     * @param listId listId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("blob|POST|/blob/object/list/{param}")
    public <T> @Nullable T get(String listId, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Blob.POST_BLOB_OBJECT_LIST_PARAM, List.of(listId), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /blob/object/list/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param listId listId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String listId, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Blob.POST_BLOB_OBJECT_LIST_PARAM, List.of(listId), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /blob/object/list/{param}} without query parameters.
     * @param <T> decoded response type
     * @param listId listId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String listId, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return get(listId, QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /blob/object/list/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param listId listId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String listId, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return get(listId, QueryParams.empty(), body, responseType);
    }
}
