package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;
import java.nio.file.Path;
import java.util.Map;

/** Contract operations for blob/object. Generated by scripts/generate_endpoints.py. */
public final class BlobObjectClient extends ServiceClient {
    BlobObjectClient(ApiClient client) {
        super(ApiService.BLOB, client);
    }

    /** Returns the client for the nested resource.
     * @return the info resource client
     */
    public BlobObjectInfoClient info() {
        return new BlobObjectInfoClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the list resource client
     */
    public BlobObjectListClient list() {
        return new BlobObjectListClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the sign resource client
     */
    public BlobObjectSignClient sign() {
        return new BlobObjectSignClient(client());
    }

    /**
     * Calls the contract route {@code DELETE /blob/object/{param}/{param}}.
     * @param <T> decoded response type
     * @param objectId objectId supplied to the operation
     * @param objectId2 objectId2 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("blob|DELETE|/blob/object/{param}/{param}")
    public <T> @Nullable T delete(String objectId, String objectId2, QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Blob.DELETE_BLOB_OBJECT_PARAM_PARAM, List.of(objectId, objectId2), query, null, responseType);
    }
    /**
     * Calls the contract route {@code DELETE /blob/object/{param}/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param objectId objectId supplied to the operation
     * @param objectId2 objectId2 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T delete(String objectId, String objectId2, QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Blob.DELETE_BLOB_OBJECT_PARAM_PARAM, List.of(objectId, objectId2), query, null, responseType);
    }
    /**
     * Calls the contract route {@code DELETE /blob/object/{param}/{param}} without query parameters.
     * @param <T> decoded response type
     * @param objectId objectId supplied to the operation
     * @param objectId2 objectId2 supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T delete(String objectId, String objectId2, Class<T> responseType) throws IOException, InterruptedException {
        return delete(objectId, objectId2, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code DELETE /blob/object/{param}/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param objectId objectId supplied to the operation
     * @param objectId2 objectId2 supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T delete(String objectId, String objectId2, TypeReference<T> responseType) throws IOException, InterruptedException {
        return delete(objectId, objectId2, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /blob/object/{param}/{param}}.
     * @param <T> decoded response type
     * @param objectId objectId supplied to the operation
     * @param objectId2 objectId2 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("blob|GET|/blob/object/{param}/{param}")
    public <T> @Nullable T get(String objectId, String objectId2, QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Blob.GET_BLOB_OBJECT_PARAM_PARAM, List.of(objectId, objectId2), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /blob/object/{param}/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param objectId objectId supplied to the operation
     * @param objectId2 objectId2 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String objectId, String objectId2, QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Blob.GET_BLOB_OBJECT_PARAM_PARAM, List.of(objectId, objectId2), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /blob/object/{param}/{param}} without query parameters.
     * @param <T> decoded response type
     * @param objectId objectId supplied to the operation
     * @param objectId2 objectId2 supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String objectId, String objectId2, Class<T> responseType) throws IOException, InterruptedException {
        return get(objectId, objectId2, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /blob/object/{param}/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param objectId objectId supplied to the operation
     * @param objectId2 objectId2 supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String objectId, String objectId2, TypeReference<T> responseType) throws IOException, InterruptedException {
        return get(objectId, objectId2, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code POST /blob/object/copy}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("blob|POST|/blob/object/copy")
    public <T> @Nullable T copy(QueryParams query, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Blob.POST_BLOB_OBJECT_COPY, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /blob/object/copy} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T copy(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Blob.POST_BLOB_OBJECT_COPY, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /blob/object/copy} without query parameters.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T copy(@Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return copy(QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /blob/object/copy} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T copy(@Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return copy(QueryParams.empty(), body, responseType);
    }

    /**
     * Calls the contract route {@code POST /blob/object/move}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("blob|POST|/blob/object/move")
    public <T> @Nullable T move(QueryParams query, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Blob.POST_BLOB_OBJECT_MOVE, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /blob/object/move} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T move(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Blob.POST_BLOB_OBJECT_MOVE, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /blob/object/move} without query parameters.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T move(@Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return move(QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /blob/object/move} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T move(@Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return move(QueryParams.empty(), body, responseType);
    }

    /**
     * Calls the contract route {@code POSTFORMDATA /blob/object/{param}/{param}}.
     * @param <T> decoded response type
     * @param objectId objectId supplied to the operation
     * @param objectId2 objectId2 supplied to the operation
     * @param query query supplied to the operation
     * @param fields fields supplied to the operation
     * @param files files supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("blob|POSTFORMDATA|/blob/object/{param}/{param}")
    public <T> @Nullable T get2(String objectId, String objectId2, QueryParams query, Map<String, String> fields, Map<String, Path> files, Class<T> responseType) throws IOException, InterruptedException {
        return requestForm(Endpoints.Blob.POSTFORMDATA_BLOB_OBJECT_PARAM_PARAM, List.of(objectId, objectId2), query, fields, files, responseType);
    }
    /**
     * Calls the contract route {@code POSTFORMDATA /blob/object/{param}/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param objectId objectId supplied to the operation
     * @param objectId2 objectId2 supplied to the operation
     * @param query query supplied to the operation
     * @param fields fields supplied to the operation
     * @param files files supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get2(String objectId, String objectId2, QueryParams query, Map<String, String> fields, Map<String, Path> files, TypeReference<T> responseType) throws IOException, InterruptedException {
        return requestForm(Endpoints.Blob.POSTFORMDATA_BLOB_OBJECT_PARAM_PARAM, List.of(objectId, objectId2), query, fields, files, responseType);
    }
    /**
     * Calls the contract route {@code POSTFORMDATA /blob/object/{param}/{param}} without query parameters.
     * @param <T> decoded response type
     * @param objectId objectId supplied to the operation
     * @param objectId2 objectId2 supplied to the operation
     * @param fields fields supplied to the operation
     * @param files files supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get2(String objectId, String objectId2, Map<String, String> fields, Map<String, Path> files, Class<T> responseType) throws IOException, InterruptedException {
        return get2(objectId, objectId2, QueryParams.empty(), fields, files, responseType);
    }
    /**
     * Calls the contract route {@code POSTFORMDATA /blob/object/{param}/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param objectId objectId supplied to the operation
     * @param objectId2 objectId2 supplied to the operation
     * @param fields fields supplied to the operation
     * @param files files supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get2(String objectId, String objectId2, Map<String, String> fields, Map<String, Path> files, TypeReference<T> responseType) throws IOException, InterruptedException {
        return get2(objectId, objectId2, QueryParams.empty(), fields, files, responseType);
    }

}
