package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for blob/object/sign. Generated by scripts/generate_endpoints.py. */
public final class BlobObjectSignClient extends ServiceClient {
    BlobObjectSignClient(ApiClient client) {
        super(ApiService.BLOB, client);
    }

    /**
     * Calls the contract route {@code POST /blob/object/sign/{param}/{param}}.
     * @param <T> decoded response type
     * @param signId signId supplied to the operation
     * @param signId2 signId2 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("blob|POST|/blob/object/sign/{param}/{param}")
    public <T> @Nullable T get(String signId, String signId2, QueryParams query, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Blob.POST_BLOB_OBJECT_SIGN_PARAM_PARAM, List.of(signId, signId2), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /blob/object/sign/{param}/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param signId signId supplied to the operation
     * @param signId2 signId2 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String signId, String signId2, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Blob.POST_BLOB_OBJECT_SIGN_PARAM_PARAM, List.of(signId, signId2), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /blob/object/sign/{param}/{param}} without query parameters.
     * @param <T> decoded response type
     * @param signId signId supplied to the operation
     * @param signId2 signId2 supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String signId, String signId2, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return get(signId, signId2, QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /blob/object/sign/{param}/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param signId signId supplied to the operation
     * @param signId2 signId2 supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String signId, String signId2, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return get(signId, signId2, QueryParams.empty(), body, responseType);
    }

}
