package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for connectors. Generated by scripts/generate_endpoints.py. */
public final class ConnectorsClient extends ServiceClient {
    ConnectorsClient(ApiClient client) {
        super(ApiService.CONNECTORS, client);
    }

    /** Returns the client for the nested resource.
     * @return the catalog resource client
     */
    public ConnectorsCatalogClient catalog() {
        return new ConnectorsCatalogClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the connection-tests resource client
     */
    public ConnectorsConnectionTestsClient connectionTests() {
        return new ConnectorsConnectionTestsClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the diagnostics resource client
     */
    public ConnectorsDiagnosticsClient diagnostics() {
        return new ConnectorsDiagnosticsClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the installations resource client
     */
    public ConnectorsInstallationsClient installations() {
        return new ConnectorsInstallationsClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the sync-runs resource client
     */
    public ConnectorsSyncRunsClient syncRuns() {
        return new ConnectorsSyncRunsClient(client());
    }

    /**
     * Calls the contract route {@code GET /connectors/catalog}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("connectors|GET|/connectors/catalog")
    public <T> @Nullable T getCatalog(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Connectors.GET_CONNECTORS_CATALOG, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /connectors/catalog} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getCatalog(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Connectors.GET_CONNECTORS_CATALOG, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /connectors/catalog} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getCatalog(Class<T> responseType) throws IOException, InterruptedException {
        return getCatalog(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /connectors/catalog} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getCatalog(TypeReference<T> responseType) throws IOException, InterruptedException {
        return getCatalog(QueryParams.empty(), responseType);
    }
}
