package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for connectors/sync-runs. Generated by scripts/generate_endpoints.py. */
public final class ConnectorsSyncRunsClient extends ServiceClient {
    ConnectorsSyncRunsClient(ApiClient client) {
        super(ApiService.CONNECTORS, client);
    }

    /**
     * Calls the contract route {@code POST /connectors/sync-runs/{param}/replay}.
     * @param <T> decoded response type
     * @param syncRunId syncRunId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("connectors|POST|/connectors/sync-runs/{param}/replay")
    public <T> @Nullable T replay(String syncRunId, QueryParams query, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Connectors.POST_CONNECTORS_SYNC_RUNS_PARAM_REPLAY, List.of(syncRunId), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /connectors/sync-runs/{param}/replay} using a generic response type.
     * @param <T> decoded response type
     * @param syncRunId syncRunId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T replay(String syncRunId, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Connectors.POST_CONNECTORS_SYNC_RUNS_PARAM_REPLAY, List.of(syncRunId), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /connectors/sync-runs/{param}/replay} without query parameters.
     * @param <T> decoded response type
     * @param syncRunId syncRunId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T replay(String syncRunId, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return replay(syncRunId, QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /connectors/sync-runs/{param}/replay} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param syncRunId syncRunId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T replay(String syncRunId, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return replay(syncRunId, QueryParams.empty(), body, responseType);
    }

}
