package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for data/archival/archival/policies. Generated by scripts/generate_endpoints.py. */
public final class DataArchivalArchivalPoliciesClient extends ServiceClient {
    DataArchivalArchivalPoliciesClient(ApiClient client) {
        super(ApiService.DATA, client);
    }

    /** Returns the client for the nested resource.
     * @return the executions resource client
     */
    public DataArchivalArchivalPoliciesExecutionsClient executions() {
        return new DataArchivalArchivalPoliciesExecutionsClient(client());
    }

    /**
     * Calls the contract route {@code GET /data/archival/archival/policies}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("data|GET|/data/archival/archival/policies")
    public <T> @Nullable T list(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Data.GET_DATA_ARCHIVAL_ARCHIVAL_POLICIES, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/archival/archival/policies} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Data.GET_DATA_ARCHIVAL_ARCHIVAL_POLICIES, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/archival/archival/policies} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(Class<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /data/archival/archival/policies} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(TypeReference<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /data/archival/archival/policies/{param}}.
     * @param <T> decoded response type
     * @param policyId policyId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("data|GET|/data/archival/archival/policies/{param}")
    public <T> @Nullable T get(String policyId, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Data.GET_DATA_ARCHIVAL_ARCHIVAL_POLICIES_PARAM, List.of(policyId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/archival/archival/policies/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param policyId policyId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String policyId, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Data.GET_DATA_ARCHIVAL_ARCHIVAL_POLICIES_PARAM, List.of(policyId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/archival/archival/policies/{param}} without query parameters.
     * @param <T> decoded response type
     * @param policyId policyId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String policyId, Class<T> responseType) throws IOException, InterruptedException {
        return get(policyId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /data/archival/archival/policies/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param policyId policyId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String policyId, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return get(policyId, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code POST /data/archival/archival/policies}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("data|POST|/data/archival/archival/policies")
    public <T> @Nullable T create(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Data.POST_DATA_ARCHIVAL_ARCHIVAL_POLICIES, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /data/archival/archival/policies} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Data.POST_DATA_ARCHIVAL_ARCHIVAL_POLICIES, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /data/archival/archival/policies} without query parameters.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(@Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return create(QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /data/archival/archival/policies} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(@Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return create(QueryParams.empty(), body, responseType);
    }
}
