package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for data/pipelines/pipelines. Generated by scripts/generate_endpoints.py. */
public final class DataPipelinesPipelinesClient extends ServiceClient {
    DataPipelinesPipelinesClient(ApiClient client) {
        super(ApiService.DATA, client);
    }

    /**
     * Calls the contract route {@code GET /data/pipelines/pipelines}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("data|GET|/data/pipelines/pipelines")
    public <T> @Nullable T list(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Data.GET_DATA_PIPELINES_PIPELINES, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/pipelines/pipelines} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Data.GET_DATA_PIPELINES_PIPELINES, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/pipelines/pipelines} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(Class<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /data/pipelines/pipelines} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(TypeReference<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /data/pipelines/pipelines/{param}}.
     * @param <T> decoded response type
     * @param definitionId definitionId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("data|GET|/data/pipelines/pipelines/{param}")
    public <T> @Nullable T get(String definitionId, QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Data.GET_DATA_PIPELINES_PIPELINES_PARAM, List.of(definitionId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/pipelines/pipelines/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param definitionId definitionId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String definitionId, QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Data.GET_DATA_PIPELINES_PIPELINES_PARAM, List.of(definitionId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/pipelines/pipelines/{param}} without query parameters.
     * @param <T> decoded response type
     * @param definitionId definitionId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String definitionId, Class<T> responseType) throws IOException, InterruptedException {
        return get(definitionId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /data/pipelines/pipelines/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param definitionId definitionId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String definitionId, TypeReference<T> responseType) throws IOException, InterruptedException {
        return get(definitionId, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code POST /data/pipelines/pipelines}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("data|POST|/data/pipelines/pipelines")
    public <T> @Nullable T create(QueryParams query, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Data.POST_DATA_PIPELINES_PIPELINES, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /data/pipelines/pipelines} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Data.POST_DATA_PIPELINES_PIPELINES, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /data/pipelines/pipelines} without query parameters.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(@Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return create(QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /data/pipelines/pipelines} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(@Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return create(QueryParams.empty(), body, responseType);
    }

}
