package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for data/archival. Generated by scripts/generate_endpoints.py. */
public final class DataArchivalClient extends ServiceClient {
    DataArchivalClient(ApiClient client) {
        super(ApiService.DATA, client);
    }

    /** Returns the client for the nested resource.
     * @return the archival resource client
     */
    public DataArchivalArchivalClient archival() {
        return new DataArchivalArchivalClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the capabilities resource client
     */
    public DataArchivalCapabilitiesClient capabilities() {
        return new DataArchivalCapabilitiesClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the runs resource client
     */
    public DataArchivalRunsClient runs() {
        return new DataArchivalRunsClient(client());
    }

    /**
     * Calls the contract route {@code GET /data/archival/health}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("data|GET|/data/archival/health")
    public <T> @Nullable T health(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Data.GET_DATA_ARCHIVAL_HEALTH, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/archival/health} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T health(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Data.GET_DATA_ARCHIVAL_HEALTH, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/archival/health} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T health(Class<T> responseType) throws IOException, InterruptedException {
        return health(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /data/archival/health} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T health(TypeReference<T> responseType) throws IOException, InterruptedException {
        return health(QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /data/archival/info}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("data|GET|/data/archival/info")
    public <T> @Nullable T getInfo(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Data.GET_DATA_ARCHIVAL_INFO, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/archival/info} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getInfo(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Data.GET_DATA_ARCHIVAL_INFO, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/archival/info} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getInfo(Class<T> responseType) throws IOException, InterruptedException {
        return getInfo(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /data/archival/info} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getInfo(TypeReference<T> responseType) throws IOException, InterruptedException {
        return getInfo(QueryParams.empty(), responseType);
    }
}
