package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for data/enrichment/enrichment/profiles. Generated by scripts/generate_endpoints.py. */
public final class DataEnrichmentEnrichmentProfilesClient extends ServiceClient {
    DataEnrichmentEnrichmentProfilesClient(ApiClient client) {
        super(ApiService.DATA, client);
    }

    /** Returns the client for the nested resource.
     * @return the executions resource client
     */
    public DataEnrichmentEnrichmentProfilesExecutionsClient executions() {
        return new DataEnrichmentEnrichmentProfilesExecutionsClient(client());
    }

    /**
     * Calls the contract route {@code GET /data/enrichment/enrichment/profiles}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("data|GET|/data/enrichment/enrichment/profiles")
    public <T> @Nullable T list(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Data.GET_DATA_ENRICHMENT_ENRICHMENT_PROFILES, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/enrichment/enrichment/profiles} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Data.GET_DATA_ENRICHMENT_ENRICHMENT_PROFILES, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/enrichment/enrichment/profiles} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(Class<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /data/enrichment/enrichment/profiles} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(TypeReference<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /data/enrichment/enrichment/profiles/{param}}.
     * @param <T> decoded response type
     * @param profileId profileId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("data|GET|/data/enrichment/enrichment/profiles/{param}")
    public <T> @Nullable T get(String profileId, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Data.GET_DATA_ENRICHMENT_ENRICHMENT_PROFILES_PARAM,
                List.of(profileId),
                query,
                null,
                responseType);
    }
    /**
     * Calls the contract route {@code GET /data/enrichment/enrichment/profiles/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param profileId profileId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String profileId, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Data.GET_DATA_ENRICHMENT_ENRICHMENT_PROFILES_PARAM,
                List.of(profileId),
                query,
                null,
                responseType);
    }
    /**
     * Calls the contract route {@code GET /data/enrichment/enrichment/profiles/{param}} without query parameters.
     * @param <T> decoded response type
     * @param profileId profileId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String profileId, Class<T> responseType) throws IOException, InterruptedException {
        return get(profileId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /data/enrichment/enrichment/profiles/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param profileId profileId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String profileId, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return get(profileId, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code POST /data/enrichment/enrichment/profiles}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("data|POST|/data/enrichment/enrichment/profiles")
    public <T> @Nullable T create(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Data.POST_DATA_ENRICHMENT_ENRICHMENT_PROFILES, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /data/enrichment/enrichment/profiles} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Data.POST_DATA_ENRICHMENT_ENRICHMENT_PROFILES, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /data/enrichment/enrichment/profiles} without query parameters.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(@Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return create(QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /data/enrichment/enrichment/profiles} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(@Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return create(QueryParams.empty(), body, responseType);
    }
}
