package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for data/sync/sync/jobs. Generated by scripts/generate_endpoints.py. */
public final class DataSyncSyncJobsClient extends ServiceClient {
    DataSyncSyncJobsClient(ApiClient client) {
        super(ApiService.DATA, client);
    }

    /** Returns the client for the nested resource.
     * @return the executions resource client
     */
    public DataSyncSyncJobsExecutionsClient executions() {
        return new DataSyncSyncJobsExecutionsClient(client());
    }

    /**
     * Calls the contract route {@code GET /data/sync/sync/jobs}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("data|GET|/data/sync/sync/jobs")
    public <T> @Nullable T list(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Data.GET_DATA_SYNC_SYNC_JOBS, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/sync/sync/jobs} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Data.GET_DATA_SYNC_SYNC_JOBS, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/sync/sync/jobs} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(Class<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /data/sync/sync/jobs} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(TypeReference<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /data/sync/sync/jobs/{param}}.
     * @param <T> decoded response type
     * @param jobId jobId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("data|GET|/data/sync/sync/jobs/{param}")
    public <T> @Nullable T get(String jobId, QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Data.GET_DATA_SYNC_SYNC_JOBS_PARAM, List.of(jobId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/sync/sync/jobs/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param jobId jobId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String jobId, QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Data.GET_DATA_SYNC_SYNC_JOBS_PARAM, List.of(jobId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/sync/sync/jobs/{param}} without query parameters.
     * @param <T> decoded response type
     * @param jobId jobId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String jobId, Class<T> responseType) throws IOException, InterruptedException {
        return get(jobId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /data/sync/sync/jobs/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param jobId jobId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String jobId, TypeReference<T> responseType) throws IOException, InterruptedException {
        return get(jobId, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code POST /data/sync/sync/jobs}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("data|POST|/data/sync/sync/jobs")
    public <T> @Nullable T create(QueryParams query, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Data.POST_DATA_SYNC_SYNC_JOBS, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /data/sync/sync/jobs} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Data.POST_DATA_SYNC_SYNC_JOBS, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /data/sync/sync/jobs} without query parameters.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(@Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return create(QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /data/sync/sync/jobs} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(@Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return create(QueryParams.empty(), body, responseType);
    }

}
