package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for data/ingest/datasets/artifacts. Generated by scripts/generate_endpoints.py. */
public final class DataIngestDatasetsArtifactsClient extends ServiceClient {
    DataIngestDatasetsArtifactsClient(ApiClient client) {
        super(ApiService.DATA, client);
    }

    /**
     * Calls the contract route {@code GET /data/ingest/datasets/{param}/artifacts/{param}/content}.
     * @param <T> decoded response type
     * @param datasetId datasetId supplied to the operation
     * @param manifestId manifestId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("data|GET|/data/ingest/datasets/{param}/artifacts/{param}/content")
    public <T> @Nullable T getContent(String datasetId, String manifestId, QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Data.GET_DATA_INGEST_DATASETS_PARAM_ARTIFACTS_PARAM_CONTENT, List.of(datasetId, manifestId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/ingest/datasets/{param}/artifacts/{param}/content} using a generic response type.
     * @param <T> decoded response type
     * @param datasetId datasetId supplied to the operation
     * @param manifestId manifestId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getContent(String datasetId, String manifestId, QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Data.GET_DATA_INGEST_DATASETS_PARAM_ARTIFACTS_PARAM_CONTENT, List.of(datasetId, manifestId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/ingest/datasets/{param}/artifacts/{param}/content} without query parameters.
     * @param <T> decoded response type
     * @param datasetId datasetId supplied to the operation
     * @param manifestId manifestId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getContent(String datasetId, String manifestId, Class<T> responseType) throws IOException, InterruptedException {
        return getContent(datasetId, manifestId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /data/ingest/datasets/{param}/artifacts/{param}/content} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param datasetId datasetId supplied to the operation
     * @param manifestId manifestId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getContent(String datasetId, String manifestId, TypeReference<T> responseType) throws IOException, InterruptedException {
        return getContent(datasetId, manifestId, QueryParams.empty(), responseType);
    }

}
