package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for data/ingest/datasets. Generated by scripts/generate_endpoints.py. */
public final class DataIngestDatasetsClient extends ServiceClient {
    DataIngestDatasetsClient(ApiClient client) {
        super(ApiService.DATA, client);
    }

    /** Returns the client for the nested resource.
     * @return the artifacts resource client
     */
    public DataIngestDatasetsArtifactsClient artifacts() {
        return new DataIngestDatasetsArtifactsClient(client());
    }

    /**
     * Calls the contract route {@code GET /data/ingest/datasets}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("data|GET|/data/ingest/datasets")
    public <T> @Nullable T list(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Data.GET_DATA_INGEST_DATASETS, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/ingest/datasets} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Data.GET_DATA_INGEST_DATASETS, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/ingest/datasets} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(Class<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /data/ingest/datasets} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(TypeReference<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /data/ingest/datasets/{param}}.
     * @param <T> decoded response type
     * @param datasetId datasetId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("data|GET|/data/ingest/datasets/{param}")
    public <T> @Nullable T get(String datasetId, QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Data.GET_DATA_INGEST_DATASETS_PARAM, List.of(datasetId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/ingest/datasets/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param datasetId datasetId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String datasetId, QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Data.GET_DATA_INGEST_DATASETS_PARAM, List.of(datasetId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/ingest/datasets/{param}} without query parameters.
     * @param <T> decoded response type
     * @param datasetId datasetId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String datasetId, Class<T> responseType) throws IOException, InterruptedException {
        return get(datasetId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /data/ingest/datasets/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param datasetId datasetId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String datasetId, TypeReference<T> responseType) throws IOException, InterruptedException {
        return get(datasetId, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code POST /data/ingest/datasets/ingest}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("data|POST|/data/ingest/datasets/ingest")
    public <T> @Nullable T ingest(QueryParams query, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Data.POST_DATA_INGEST_DATASETS_INGEST, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /data/ingest/datasets/ingest} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T ingest(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Data.POST_DATA_INGEST_DATASETS_INGEST, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /data/ingest/datasets/ingest} without query parameters.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T ingest(@Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return ingest(QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /data/ingest/datasets/ingest} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T ingest(@Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return ingest(QueryParams.empty(), body, responseType);
    }

}
