package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for data/catalog/catalog. Generated by scripts/generate_endpoints.py. */
public final class DataCatalogCatalogClient extends ServiceClient {
    DataCatalogCatalogClient(ApiClient client) {
        super(ApiService.DATA, client);
    }

    /** Returns the client for the nested resource.
     * @return the datasets resource client
     */
    public DataCatalogCatalogDatasetsClient datasets() {
        return new DataCatalogCatalogDatasetsClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the sources resource client
     */
    public DataCatalogCatalogSourcesClient sources() {
        return new DataCatalogCatalogSourcesClient(client());
    }

}
