package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for events/reprocess. Generated by scripts/generate_endpoints.py. */
public final class EventsReprocessClient extends ServiceClient {
    EventsReprocessClient(ApiClient client) {
        super(ApiService.EVENTS, client);
    }

    /**
     * Calls the contract route {@code POST /events/reprocess/internal}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("events|POST|/events/reprocess/internal")
    public <T> @Nullable T createInternal(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Events.POST_EVENTS_REPROCESS_INTERNAL, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /events/reprocess/internal} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T createInternal(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Events.POST_EVENTS_REPROCESS_INTERNAL, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /events/reprocess/internal} without query parameters.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T createInternal(@Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return createInternal(QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /events/reprocess/internal} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T createInternal(@Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return createInternal(QueryParams.empty(), body, responseType);
    }
}
