package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for events/raw. Generated by scripts/generate_endpoints.py. */
public final class EventsRawClient extends ServiceClient {
    EventsRawClient(ApiClient client) {
        super(ApiService.EVENTS, client);
    }

    /** Returns the client for the nested resource.
     * @return the reprocess resource client
     */
    public EventsRawReprocessClient reprocess() {
        return new EventsRawReprocessClient(client());
    }

}
