package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for governance/roles. Generated by scripts/generate_endpoints.py. */
public final class GovernanceRolesClient extends ServiceClient {
    GovernanceRolesClient(ApiClient client) {
        super(ApiService.GOVERNANCE, client);
    }

    /**
     * Calls the contract route {@code DELETE /roles/{param}}.
     * @param <T> decoded response type
     * @param roleId roleId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("governance|DELETE|/roles/{param}")
    public <T> @Nullable T delete(String roleId, QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Governance.DELETE_ROLES_PARAM, List.of(roleId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code DELETE /roles/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param roleId roleId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T delete(String roleId, QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Governance.DELETE_ROLES_PARAM, List.of(roleId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code DELETE /roles/{param}} without query parameters.
     * @param <T> decoded response type
     * @param roleId roleId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T delete(String roleId, Class<T> responseType) throws IOException, InterruptedException {
        return delete(roleId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code DELETE /roles/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param roleId roleId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T delete(String roleId, TypeReference<T> responseType) throws IOException, InterruptedException {
        return delete(roleId, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /roles}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("governance|GET|/roles")
    public <T> @Nullable T list(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Governance.GET_ROLES, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /roles} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Governance.GET_ROLES, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /roles} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(Class<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /roles} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(TypeReference<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /roles/{param}}.
     * @param <T> decoded response type
     * @param roleId roleId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("governance|GET|/roles/{param}")
    public <T> @Nullable T get(String roleId, QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Governance.GET_ROLES_PARAM, List.of(roleId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /roles/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param roleId roleId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String roleId, QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Governance.GET_ROLES_PARAM, List.of(roleId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /roles/{param}} without query parameters.
     * @param <T> decoded response type
     * @param roleId roleId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String roleId, Class<T> responseType) throws IOException, InterruptedException {
        return get(roleId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /roles/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param roleId roleId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String roleId, TypeReference<T> responseType) throws IOException, InterruptedException {
        return get(roleId, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code POST /roles}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("governance|POST|/roles")
    public <T> @Nullable T create(QueryParams query, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Governance.POST_ROLES, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /roles} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Governance.POST_ROLES, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /roles} without query parameters.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(@Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return create(QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /roles} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(@Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return create(QueryParams.empty(), body, responseType);
    }

}
