package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for governance/compliance. Generated by scripts/generate_endpoints.py. */
public final class GovernanceComplianceClient extends ServiceClient {
    GovernanceComplianceClient(ApiClient client) {
        super(ApiService.GOVERNANCE, client);
    }

    /** Returns the client for the nested resource.
     * @return the assessments resource client
     */
    public GovernanceComplianceAssessmentsClient assessments() {
        return new GovernanceComplianceAssessmentsClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the frameworks resource client
     */
    public GovernanceComplianceFrameworksClient frameworks() {
        return new GovernanceComplianceFrameworksClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the violations resource client
     */
    public GovernanceComplianceViolationsClient violations() {
        return new GovernanceComplianceViolationsClient(client());
    }

    /**
     * Calls the contract route {@code GET /compliance/score}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("governance|GET|/compliance/score")
    public <T> @Nullable T getScore(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Governance.GET_COMPLIANCE_SCORE, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /compliance/score} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getScore(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Governance.GET_COMPLIANCE_SCORE, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /compliance/score} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getScore(Class<T> responseType) throws IOException, InterruptedException {
        return getScore(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /compliance/score} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getScore(TypeReference<T> responseType) throws IOException, InterruptedException {
        return getScore(QueryParams.empty(), responseType);
    }
}
