package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for governance/permissions. Generated by scripts/generate_endpoints.py. */
public final class GovernancePermissionsClient extends ServiceClient {
    GovernancePermissionsClient(ApiClient client) {
        super(ApiService.GOVERNANCE, client);
    }

    /**
     * Calls the contract route {@code GET /permissions}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("governance|GET|/permissions")
    public <T> @Nullable T list(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Governance.GET_PERMISSIONS, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /permissions} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Governance.GET_PERMISSIONS, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /permissions} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(Class<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /permissions} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(TypeReference<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /permissions/{param}}.
     * @param <T> decoded response type
     * @param permissionId permissionId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("governance|GET|/permissions/{param}")
    public <T> @Nullable T get(String permissionId, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Governance.GET_PERMISSIONS_PARAM, List.of(permissionId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /permissions/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param permissionId permissionId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String permissionId, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Governance.GET_PERMISSIONS_PARAM, List.of(permissionId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /permissions/{param}} without query parameters.
     * @param <T> decoded response type
     * @param permissionId permissionId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String permissionId, Class<T> responseType) throws IOException, InterruptedException {
        return get(permissionId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /permissions/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param permissionId permissionId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String permissionId, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return get(permissionId, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code POST /permissions}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("governance|POST|/permissions")
    public <T> @Nullable T create(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Governance.POST_PERMISSIONS, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /permissions} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Governance.POST_PERMISSIONS, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /permissions} without query parameters.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(@Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return create(QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /permissions} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(@Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return create(QueryParams.empty(), body, responseType);
    }
}
