package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Named contract operations for the invocations service. Generated by scripts/generate_endpoints.py. */
public final class InvocationsClient extends ServiceClient {
    InvocationsClient(ApiClient client) {
        super(ApiService.INVOCATIONS, client);
    }

    /**
     * Calls the contract route {@code POST /invocations}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("invocations|POST|/invocations")
    public <T> @Nullable T postInvocations(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Invocations.POST_INVOCATIONS, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /invocations}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postInvocations(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Invocations.POST_INVOCATIONS, List.of(), query, body, responseType);
    }
}
