package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Named contract operations for the lineage service. Generated by scripts/generate_endpoints.py. */
public final class LineageClient extends ServiceClient {
    LineageClient(ApiClient client) {
        super(ApiService.LINEAGE, client);
    }

    /**
     * Calls the contract route {@code GET /lineage/edges}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("lineage|GET|/lineage/edges")
    public <T> @Nullable T getLineageEdges(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Lineage.GET_LINEAGE_EDGES, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /lineage/edges}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getLineageEdges(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Lineage.GET_LINEAGE_EDGES, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /lineage/edges/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("lineage|GET|/lineage/edges/{param}")
    public <T> @Nullable T getLineageEdgesParam(String pathParam1, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Lineage.GET_LINEAGE_EDGES_PARAM, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /lineage/edges/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getLineageEdgesParam(String pathParam1, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Lineage.GET_LINEAGE_EDGES_PARAM, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /lineage/graph}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("lineage|GET|/lineage/graph")
    public <T> @Nullable T getLineageGraph(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Lineage.GET_LINEAGE_GRAPH, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /lineage/graph}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getLineageGraph(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Lineage.GET_LINEAGE_GRAPH, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /lineage/nodes}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("lineage|GET|/lineage/nodes")
    public <T> @Nullable T getLineageNodes(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Lineage.GET_LINEAGE_NODES, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /lineage/nodes}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getLineageNodes(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Lineage.GET_LINEAGE_NODES, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /lineage/nodes/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("lineage|GET|/lineage/nodes/{param}")
    public <T> @Nullable T getLineageNodesParam(String pathParam1, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Lineage.GET_LINEAGE_NODES_PARAM, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /lineage/nodes/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getLineageNodesParam(String pathParam1, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Lineage.GET_LINEAGE_NODES_PARAM, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /lineage/nodes/{param}/trace}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("lineage|GET|/lineage/nodes/{param}/trace")
    public <T> @Nullable T getLineageNodesParamTrace(String pathParam1, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Lineage.GET_LINEAGE_NODES_PARAM_TRACE, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /lineage/nodes/{param}/trace}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getLineageNodesParamTrace(
            String pathParam1, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Lineage.GET_LINEAGE_NODES_PARAM_TRACE, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code POST /lineage/impact}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("lineage|POST|/lineage/impact")
    public <T> @Nullable T postLineageImpact(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Lineage.POST_LINEAGE_IMPACT, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /lineage/impact}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postLineageImpact(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Lineage.POST_LINEAGE_IMPACT, List.of(), query, body, responseType);
    }
}
