package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for observability/alerts/incidents. Generated by scripts/generate_endpoints.py. */
public final class ObservabilityAlertsIncidentsClient extends ServiceClient {
    ObservabilityAlertsIncidentsClient(ApiClient client) {
        super(ApiService.OBSERVABILITY, client);
    }

    /**
     * Calls the contract route {@code GET /observability/alerts/incidents}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|GET|/observability/alerts/incidents")
    public <T> @Nullable T list(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.GET_OBSERVABILITY_ALERTS_INCIDENTS, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /observability/alerts/incidents} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.GET_OBSERVABILITY_ALERTS_INCIDENTS, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /observability/alerts/incidents} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(Class<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /observability/alerts/incidents} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(TypeReference<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }
}
