package dev.frontal.sdk;

/** Contract operations for observability. Generated by scripts/generate_endpoints.py. */
public final class ObservabilityClient extends ServiceClient {
    ObservabilityClient(ApiClient client) {
        super(ApiService.OBSERVABILITY, client);
    }

    /** Returns the client for the nested resource.
     * @return the alerts resource client
     */
    public ObservabilityAlertsClient alerts() {
        return new ObservabilityAlertsClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the dashboards resource client
     */
    public ObservabilityDashboardsClient dashboards() {
        return new ObservabilityDashboardsClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the events resource client
     */
    public ObservabilityEventsClient events() {
        return new ObservabilityEventsClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the logs resource client
     */
    public ObservabilityLogsClient logs() {
        return new ObservabilityLogsClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the metrics resource client
     */
    public ObservabilityMetricsClient metrics() {
        return new ObservabilityMetricsClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the traces resource client
     */
    public ObservabilityTracesClient traces() {
        return new ObservabilityTracesClient(client());
    }
}
