package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for observability/dashboards. Generated by scripts/generate_endpoints.py. */
public final class ObservabilityDashboardsClient extends ServiceClient {
    ObservabilityDashboardsClient(ApiClient client) {
        super(ApiService.OBSERVABILITY, client);
    }

    /**
     * Calls the contract route {@code DELETE /observability/dashboards/{param}}.
     * @param <T> decoded response type
     * @param dashboardId dashboardId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|DELETE|/observability/dashboards/{param}")
    public <T> @Nullable T delete(String dashboardId, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.DELETE_OBSERVABILITY_DASHBOARDS_PARAM,
                List.of(dashboardId),
                query,
                null,
                responseType);
    }
    /**
     * Calls the contract route {@code DELETE /observability/dashboards/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param dashboardId dashboardId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T delete(String dashboardId, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.DELETE_OBSERVABILITY_DASHBOARDS_PARAM,
                List.of(dashboardId),
                query,
                null,
                responseType);
    }
    /**
     * Calls the contract route {@code DELETE /observability/dashboards/{param}} without query parameters.
     * @param <T> decoded response type
     * @param dashboardId dashboardId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T delete(String dashboardId, Class<T> responseType) throws IOException, InterruptedException {
        return delete(dashboardId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code DELETE /observability/dashboards/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param dashboardId dashboardId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T delete(String dashboardId, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return delete(dashboardId, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /observability/dashboards}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|GET|/observability/dashboards")
    public <T> @Nullable T list(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Observability.GET_OBSERVABILITY_DASHBOARDS, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /observability/dashboards} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.GET_OBSERVABILITY_DASHBOARDS, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /observability/dashboards} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(Class<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /observability/dashboards} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(TypeReference<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /observability/dashboards/{param}}.
     * @param <T> decoded response type
     * @param dashboardId dashboardId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|GET|/observability/dashboards/{param}")
    public <T> @Nullable T get(String dashboardId, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.GET_OBSERVABILITY_DASHBOARDS_PARAM,
                List.of(dashboardId),
                query,
                null,
                responseType);
    }
    /**
     * Calls the contract route {@code GET /observability/dashboards/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param dashboardId dashboardId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String dashboardId, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.GET_OBSERVABILITY_DASHBOARDS_PARAM,
                List.of(dashboardId),
                query,
                null,
                responseType);
    }
    /**
     * Calls the contract route {@code GET /observability/dashboards/{param}} without query parameters.
     * @param <T> decoded response type
     * @param dashboardId dashboardId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String dashboardId, Class<T> responseType) throws IOException, InterruptedException {
        return get(dashboardId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /observability/dashboards/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param dashboardId dashboardId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String dashboardId, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return get(dashboardId, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/dashboards}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|POST|/observability/dashboards")
    public <T> @Nullable T create(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.POST_OBSERVABILITY_DASHBOARDS, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /observability/dashboards} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.POST_OBSERVABILITY_DASHBOARDS, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /observability/dashboards} without query parameters.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(@Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return create(QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /observability/dashboards} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(@Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return create(QueryParams.empty(), body, responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/dashboards/{param}/share}.
     * @param <T> decoded response type
     * @param dashboardId dashboardId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|POST|/observability/dashboards/{param}/share")
    public <T> @Nullable T share(String dashboardId, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.POST_OBSERVABILITY_DASHBOARDS_PARAM_SHARE,
                List.of(dashboardId),
                query,
                body,
                responseType);
    }
    /**
     * Calls the contract route {@code POST /observability/dashboards/{param}/share} using a generic response type.
     * @param <T> decoded response type
     * @param dashboardId dashboardId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T share(
            String dashboardId, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.POST_OBSERVABILITY_DASHBOARDS_PARAM_SHARE,
                List.of(dashboardId),
                query,
                body,
                responseType);
    }
    /**
     * Calls the contract route {@code POST /observability/dashboards/{param}/share} without query parameters.
     * @param <T> decoded response type
     * @param dashboardId dashboardId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T share(String dashboardId, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return share(dashboardId, QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /observability/dashboards/{param}/share} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param dashboardId dashboardId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T share(String dashboardId, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return share(dashboardId, QueryParams.empty(), body, responseType);
    }

    /**
     * Calls the contract route {@code PUT /observability/dashboards/{param}}.
     * @param <T> decoded response type
     * @param dashboardId dashboardId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|PUT|/observability/dashboards/{param}")
    public <T> @Nullable T update(String dashboardId, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.PUT_OBSERVABILITY_DASHBOARDS_PARAM,
                List.of(dashboardId),
                query,
                body,
                responseType);
    }
    /**
     * Calls the contract route {@code PUT /observability/dashboards/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param dashboardId dashboardId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T update(
            String dashboardId, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.PUT_OBSERVABILITY_DASHBOARDS_PARAM,
                List.of(dashboardId),
                query,
                body,
                responseType);
    }
    /**
     * Calls the contract route {@code PUT /observability/dashboards/{param}} without query parameters.
     * @param <T> decoded response type
     * @param dashboardId dashboardId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T update(String dashboardId, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return update(dashboardId, QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code PUT /observability/dashboards/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param dashboardId dashboardId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T update(String dashboardId, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return update(dashboardId, QueryParams.empty(), body, responseType);
    }
}
