package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for observability/alerts/rules. Generated by scripts/generate_endpoints.py. */
public final class ObservabilityAlertsRulesClient extends ServiceClient {
    ObservabilityAlertsRulesClient(ApiClient client) {
        super(ApiService.OBSERVABILITY, client);
    }

    /**
     * Calls the contract route {@code DELETE /observability/alerts/rules/{param}}.
     * @param <T> decoded response type
     * @param ruleId ruleId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|DELETE|/observability/alerts/rules/{param}")
    public <T> @Nullable T delete(String ruleId, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.DELETE_OBSERVABILITY_ALERTS_RULES_PARAM,
                List.of(ruleId),
                query,
                null,
                responseType);
    }
    /**
     * Calls the contract route {@code DELETE /observability/alerts/rules/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param ruleId ruleId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T delete(String ruleId, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.DELETE_OBSERVABILITY_ALERTS_RULES_PARAM,
                List.of(ruleId),
                query,
                null,
                responseType);
    }
    /**
     * Calls the contract route {@code DELETE /observability/alerts/rules/{param}} without query parameters.
     * @param <T> decoded response type
     * @param ruleId ruleId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T delete(String ruleId, Class<T> responseType) throws IOException, InterruptedException {
        return delete(ruleId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code DELETE /observability/alerts/rules/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param ruleId ruleId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T delete(String ruleId, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return delete(ruleId, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /observability/alerts/rules}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|GET|/observability/alerts/rules")
    public <T> @Nullable T list(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Observability.GET_OBSERVABILITY_ALERTS_RULES, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /observability/alerts/rules} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.GET_OBSERVABILITY_ALERTS_RULES, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /observability/alerts/rules} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(Class<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /observability/alerts/rules} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(TypeReference<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /observability/alerts/rules/{param}}.
     * @param <T> decoded response type
     * @param ruleId ruleId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|GET|/observability/alerts/rules/{param}")
    public <T> @Nullable T get(String ruleId, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.GET_OBSERVABILITY_ALERTS_RULES_PARAM,
                List.of(ruleId),
                query,
                null,
                responseType);
    }
    /**
     * Calls the contract route {@code GET /observability/alerts/rules/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param ruleId ruleId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String ruleId, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.GET_OBSERVABILITY_ALERTS_RULES_PARAM,
                List.of(ruleId),
                query,
                null,
                responseType);
    }
    /**
     * Calls the contract route {@code GET /observability/alerts/rules/{param}} without query parameters.
     * @param <T> decoded response type
     * @param ruleId ruleId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String ruleId, Class<T> responseType) throws IOException, InterruptedException {
        return get(ruleId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /observability/alerts/rules/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param ruleId ruleId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String ruleId, TypeReference<T> responseType) throws IOException, InterruptedException {
        return get(ruleId, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/alerts/rules}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|POST|/observability/alerts/rules")
    public <T> @Nullable T create(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.POST_OBSERVABILITY_ALERTS_RULES, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /observability/alerts/rules} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.POST_OBSERVABILITY_ALERTS_RULES, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /observability/alerts/rules} without query parameters.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(@Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return create(QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /observability/alerts/rules} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(@Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return create(QueryParams.empty(), body, responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/alerts/rules/{param}/toggle}.
     * @param <T> decoded response type
     * @param ruleId ruleId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|POST|/observability/alerts/rules/{param}/toggle")
    public <T> @Nullable T toggle(String ruleId, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.POST_OBSERVABILITY_ALERTS_RULES_PARAM_TOGGLE,
                List.of(ruleId),
                query,
                body,
                responseType);
    }
    /**
     * Calls the contract route {@code POST /observability/alerts/rules/{param}/toggle} using a generic response type.
     * @param <T> decoded response type
     * @param ruleId ruleId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T toggle(
            String ruleId, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.POST_OBSERVABILITY_ALERTS_RULES_PARAM_TOGGLE,
                List.of(ruleId),
                query,
                body,
                responseType);
    }
    /**
     * Calls the contract route {@code POST /observability/alerts/rules/{param}/toggle} without query parameters.
     * @param <T> decoded response type
     * @param ruleId ruleId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T toggle(String ruleId, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return toggle(ruleId, QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /observability/alerts/rules/{param}/toggle} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param ruleId ruleId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T toggle(String ruleId, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return toggle(ruleId, QueryParams.empty(), body, responseType);
    }

    /**
     * Calls the contract route {@code PUT /observability/alerts/rules/{param}}.
     * @param <T> decoded response type
     * @param ruleId ruleId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|PUT|/observability/alerts/rules/{param}")
    public <T> @Nullable T update(String ruleId, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.PUT_OBSERVABILITY_ALERTS_RULES_PARAM,
                List.of(ruleId),
                query,
                body,
                responseType);
    }
    /**
     * Calls the contract route {@code PUT /observability/alerts/rules/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param ruleId ruleId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T update(
            String ruleId, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.PUT_OBSERVABILITY_ALERTS_RULES_PARAM,
                List.of(ruleId),
                query,
                body,
                responseType);
    }
    /**
     * Calls the contract route {@code PUT /observability/alerts/rules/{param}} without query parameters.
     * @param <T> decoded response type
     * @param ruleId ruleId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T update(String ruleId, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return update(ruleId, QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code PUT /observability/alerts/rules/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param ruleId ruleId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T update(String ruleId, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return update(ruleId, QueryParams.empty(), body, responseType);
    }
}
