package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;
import java.util.concurrent.Flow;

/** Contract operations for observability/logs. Generated by scripts/generate_endpoints.py. */
public final class ObservabilityLogsClient extends ServiceClient {
    ObservabilityLogsClient(ApiClient client) {
        super(ApiService.OBSERVABILITY, client);
    }

    /**
     * Calls the contract route {@code POST /observability/logs/ingest}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|POST|/observability/logs/ingest")
    public <T> @Nullable T ingest(QueryParams query, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Observability.POST_OBSERVABILITY_LOGS_INGEST, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /observability/logs/ingest} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T ingest(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Observability.POST_OBSERVABILITY_LOGS_INGEST, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /observability/logs/ingest} without query parameters.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T ingest(@Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return ingest(QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /observability/logs/ingest} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T ingest(@Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return ingest(QueryParams.empty(), body, responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/logs/query}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|POST|/observability/logs/query")
    public <T> @Nullable T query(QueryParams query, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Observability.POST_OBSERVABILITY_LOGS_QUERY, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /observability/logs/query} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T query(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Observability.POST_OBSERVABILITY_LOGS_QUERY, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /observability/logs/query} without query parameters.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T query(@Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return query(QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /observability/logs/query} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T query(@Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return query(QueryParams.empty(), body, responseType);
    }

    /**
     * Opens the event stream for {@code STREAM /observability/logs/stream}.
     * @param query query supplied to the operation
     * @return a publisher that emits event data
     */
    @SdkOperation("observability|STREAM|/observability/logs/stream")
    public Flow.Publisher<String> stream(QueryParams query) {
        return streamPublisher(Endpoints.Observability.STREAM_OBSERVABILITY_LOGS_STREAM, List.of(), query);
    }
    /**
     * Opens a blocking event stream for {@code STREAM /observability/logs/stream}.
     * @param query query supplied to the operation
     * @return an iterator that must be closed
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public SseEventIterator streamBlocking(QueryParams query) throws IOException, InterruptedException {
        return streamEvents(Endpoints.Observability.STREAM_OBSERVABILITY_LOGS_STREAM, List.of(), query);
    }
    /**
     * Opens the event stream for {@code STREAM /observability/logs/stream} with no query parameters.
     * @return a publisher that emits event data
     */
    public Flow.Publisher<String> stream() {
        return stream(QueryParams.empty());
    }
    /**
     * Opens a blocking event stream for {@code STREAM /observability/logs/stream} with no query parameters.
     * @return an iterator that must be closed
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public SseEventIterator streamBlocking() throws IOException, InterruptedException {
        return streamBlocking(QueryParams.empty());
    }

}
