package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import java.util.concurrent.Flow;
import org.jspecify.annotations.Nullable;

/** Named contract operations for the observability service. Generated by scripts/generate_endpoints.py. */
public final class ObservabilityClient extends ServiceClient {
    ObservabilityClient(ApiClient client) {
        super(ApiService.OBSERVABILITY, client);
    }

    /**
     * Calls the contract route {@code DELETE /observability/alerts/rules/{param}}.
     * @param <T> decoded response type
     * @param ruleId ruleId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|DELETE|/observability/alerts/rules/{param}")
    public <T> @Nullable T deleteObservabilityAlertsRulesRuleId(String ruleId, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.DELETE_OBSERVABILITY_ALERTS_RULES_PARAM,
                List.of(ruleId),
                query,
                null,
                responseType);
    }

    /**
     * Calls the contract route {@code DELETE /observability/alerts/rules/{param}}.
     * @param <T> decoded response type
     * @param ruleId ruleId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T deleteObservabilityAlertsRulesRuleId(
            String ruleId, QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.DELETE_OBSERVABILITY_ALERTS_RULES_PARAM,
                List.of(ruleId),
                query,
                null,
                responseType);
    }

    /**
     * Calls the contract route {@code DELETE /observability/alerts/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|DELETE|/observability/alerts/{param}")
    public <T> @Nullable T deleteObservabilityAlertsParam(String pathParam1, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.DELETE_OBSERVABILITY_ALERTS_PARAM,
                List.of(pathParam1),
                query,
                null,
                responseType);
    }

    /**
     * Calls the contract route {@code DELETE /observability/alerts/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T deleteObservabilityAlertsParam(
            String pathParam1, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.DELETE_OBSERVABILITY_ALERTS_PARAM,
                List.of(pathParam1),
                query,
                null,
                responseType);
    }

    /**
     * Calls the contract route {@code DELETE /observability/dashboards/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|DELETE|/observability/dashboards/{param}")
    public <T> @Nullable T deleteObservabilityDashboardsParam(
            String pathParam1, QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.DELETE_OBSERVABILITY_DASHBOARDS_PARAM,
                List.of(pathParam1),
                query,
                null,
                responseType);
    }

    /**
     * Calls the contract route {@code DELETE /observability/dashboards/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T deleteObservabilityDashboardsParam(
            String pathParam1, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.DELETE_OBSERVABILITY_DASHBOARDS_PARAM,
                List.of(pathParam1),
                query,
                null,
                responseType);
    }

    /**
     * Calls the contract route {@code GET /observability/alerts}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|GET|/observability/alerts")
    public <T> @Nullable T getObservabilityAlerts(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.GET_OBSERVABILITY_ALERTS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /observability/alerts}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getObservabilityAlerts(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.GET_OBSERVABILITY_ALERTS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /observability/alerts/incidents}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|GET|/observability/alerts/incidents")
    public <T> @Nullable T getObservabilityAlertsIncidents(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.GET_OBSERVABILITY_ALERTS_INCIDENTS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /observability/alerts/incidents}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getObservabilityAlertsIncidents(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.GET_OBSERVABILITY_ALERTS_INCIDENTS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /observability/alerts/rules}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|GET|/observability/alerts/rules")
    public <T> @Nullable T getObservabilityAlertsRules(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.GET_OBSERVABILITY_ALERTS_RULES, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /observability/alerts/rules}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getObservabilityAlertsRules(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.GET_OBSERVABILITY_ALERTS_RULES, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /observability/alerts/rules/{param}}.
     * @param <T> decoded response type
     * @param ruleId ruleId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|GET|/observability/alerts/rules/{param}")
    public <T> @Nullable T getObservabilityAlertsRulesRuleId(String ruleId, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.GET_OBSERVABILITY_ALERTS_RULES_PARAM,
                List.of(ruleId),
                query,
                null,
                responseType);
    }

    /**
     * Calls the contract route {@code GET /observability/alerts/rules/{param}}.
     * @param <T> decoded response type
     * @param ruleId ruleId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getObservabilityAlertsRulesRuleId(
            String ruleId, QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.GET_OBSERVABILITY_ALERTS_RULES_PARAM,
                List.of(ruleId),
                query,
                null,
                responseType);
    }

    /**
     * Calls the contract route {@code GET /observability/dashboards}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|GET|/observability/dashboards")
    public <T> @Nullable T getObservabilityDashboards(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.GET_OBSERVABILITY_DASHBOARDS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /observability/dashboards}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getObservabilityDashboards(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.GET_OBSERVABILITY_DASHBOARDS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /observability/dashboards/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|GET|/observability/dashboards/{param}")
    public <T> @Nullable T getObservabilityDashboardsParam(String pathParam1, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.GET_OBSERVABILITY_DASHBOARDS_PARAM,
                List.of(pathParam1),
                query,
                null,
                responseType);
    }

    /**
     * Calls the contract route {@code GET /observability/dashboards/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getObservabilityDashboardsParam(
            String pathParam1, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.GET_OBSERVABILITY_DASHBOARDS_PARAM,
                List.of(pathParam1),
                query,
                null,
                responseType);
    }

    /**
     * Calls the contract route {@code GET /observability/events/stats}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|GET|/observability/events/stats")
    public <T> @Nullable T getObservabilityEventsStats(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.GET_OBSERVABILITY_EVENTS_STATS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /observability/events/stats}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getObservabilityEventsStats(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.GET_OBSERVABILITY_EVENTS_STATS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /observability/metrics}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|GET|/observability/metrics")
    public <T> @Nullable T getObservabilityMetrics(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.GET_OBSERVABILITY_METRICS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /observability/metrics}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getObservabilityMetrics(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.GET_OBSERVABILITY_METRICS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /observability/metrics/list}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|GET|/observability/metrics/list")
    public <T> @Nullable T getObservabilityMetricsList(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.GET_OBSERVABILITY_METRICS_LIST, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /observability/metrics/list}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getObservabilityMetricsList(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.GET_OBSERVABILITY_METRICS_LIST, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /observability/traces}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|GET|/observability/traces")
    public <T> @Nullable T getObservabilityTraces(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.GET_OBSERVABILITY_TRACES, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /observability/traces}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getObservabilityTraces(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.GET_OBSERVABILITY_TRACES, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /observability/traces/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|GET|/observability/traces/{param}")
    public <T> @Nullable T getObservabilityTracesParam(String pathParam1, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.GET_OBSERVABILITY_TRACES_PARAM, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /observability/traces/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getObservabilityTracesParam(
            String pathParam1, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.GET_OBSERVABILITY_TRACES_PARAM, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/alerts}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|POST|/observability/alerts")
    public <T> @Nullable T postObservabilityAlerts(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.POST_OBSERVABILITY_ALERTS, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/alerts}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postObservabilityAlerts(
            QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.POST_OBSERVABILITY_ALERTS, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/alerts/rules}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|POST|/observability/alerts/rules")
    public <T> @Nullable T postObservabilityAlertsRules(
            QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.POST_OBSERVABILITY_ALERTS_RULES, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/alerts/rules}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postObservabilityAlertsRules(
            QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.POST_OBSERVABILITY_ALERTS_RULES, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/alerts/rules/{param}/toggle}.
     * @param <T> decoded response type
     * @param ruleId ruleId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|POST|/observability/alerts/rules/{param}/toggle")
    public <T> @Nullable T postObservabilityAlertsRulesRuleIdToggle(
            String ruleId, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.POST_OBSERVABILITY_ALERTS_RULES_PARAM_TOGGLE,
                List.of(ruleId),
                query,
                body,
                responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/alerts/rules/{param}/toggle}.
     * @param <T> decoded response type
     * @param ruleId ruleId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postObservabilityAlertsRulesRuleIdToggle(
            String ruleId, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.POST_OBSERVABILITY_ALERTS_RULES_PARAM_TOGGLE,
                List.of(ruleId),
                query,
                body,
                responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/alerts/{param}/disable}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|POST|/observability/alerts/{param}/disable")
    public <T> @Nullable T postObservabilityAlertsParamDisable(
            String pathParam1, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.POST_OBSERVABILITY_ALERTS_PARAM_DISABLE,
                List.of(pathParam1),
                query,
                body,
                responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/alerts/{param}/disable}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postObservabilityAlertsParamDisable(
            String pathParam1, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.POST_OBSERVABILITY_ALERTS_PARAM_DISABLE,
                List.of(pathParam1),
                query,
                body,
                responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/alerts/{param}/enable}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|POST|/observability/alerts/{param}/enable")
    public <T> @Nullable T postObservabilityAlertsParamEnable(
            String pathParam1, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.POST_OBSERVABILITY_ALERTS_PARAM_ENABLE,
                List.of(pathParam1),
                query,
                body,
                responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/alerts/{param}/enable}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postObservabilityAlertsParamEnable(
            String pathParam1, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.POST_OBSERVABILITY_ALERTS_PARAM_ENABLE,
                List.of(pathParam1),
                query,
                body,
                responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/dashboards}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|POST|/observability/dashboards")
    public <T> @Nullable T postObservabilityDashboards(
            QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.POST_OBSERVABILITY_DASHBOARDS, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/dashboards}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postObservabilityDashboards(
            QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.POST_OBSERVABILITY_DASHBOARDS, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/dashboards/{param}/share}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|POST|/observability/dashboards/{param}/share")
    public <T> @Nullable T postObservabilityDashboardsParamShare(
            String pathParam1, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.POST_OBSERVABILITY_DASHBOARDS_PARAM_SHARE,
                List.of(pathParam1),
                query,
                body,
                responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/dashboards/{param}/share}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postObservabilityDashboardsParamShare(
            String pathParam1, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.POST_OBSERVABILITY_DASHBOARDS_PARAM_SHARE,
                List.of(pathParam1),
                query,
                body,
                responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/events}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|POST|/observability/events")
    public <T> @Nullable T postObservabilityEvents(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.POST_OBSERVABILITY_EVENTS, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/events}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postObservabilityEvents(
            QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.POST_OBSERVABILITY_EVENTS, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/events/batch}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|POST|/observability/events/batch")
    public <T> @Nullable T postObservabilityEventsBatch(
            QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.POST_OBSERVABILITY_EVENTS_BATCH, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/events/batch}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postObservabilityEventsBatch(
            QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.POST_OBSERVABILITY_EVENTS_BATCH, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/logs/ingest}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|POST|/observability/logs/ingest")
    public <T> @Nullable T postObservabilityLogsIngest(
            QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.POST_OBSERVABILITY_LOGS_INGEST, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/logs/ingest}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postObservabilityLogsIngest(
            QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.POST_OBSERVABILITY_LOGS_INGEST, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/logs/query}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|POST|/observability/logs/query")
    public <T> @Nullable T postObservabilityLogsQuery(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.POST_OBSERVABILITY_LOGS_QUERY, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/logs/query}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postObservabilityLogsQuery(
            QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.POST_OBSERVABILITY_LOGS_QUERY, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/metrics/ingest}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|POST|/observability/metrics/ingest")
    public <T> @Nullable T postObservabilityMetricsIngest(
            QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.POST_OBSERVABILITY_METRICS_INGEST, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/metrics/ingest}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postObservabilityMetricsIngest(
            QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.POST_OBSERVABILITY_METRICS_INGEST, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/traces/query}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|POST|/observability/traces/query")
    public <T> @Nullable T postObservabilityTracesQuery(
            QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.POST_OBSERVABILITY_TRACES_QUERY, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /observability/traces/query}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postObservabilityTracesQuery(
            QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Observability.POST_OBSERVABILITY_TRACES_QUERY, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code PUT /observability/alerts/rules/{param}}.
     * @param <T> decoded response type
     * @param ruleId ruleId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|PUT|/observability/alerts/rules/{param}")
    public <T> @Nullable T putObservabilityAlertsRulesRuleId(
            String ruleId, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.PUT_OBSERVABILITY_ALERTS_RULES_PARAM,
                List.of(ruleId),
                query,
                body,
                responseType);
    }

    /**
     * Calls the contract route {@code PUT /observability/alerts/rules/{param}}.
     * @param <T> decoded response type
     * @param ruleId ruleId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T putObservabilityAlertsRulesRuleId(
            String ruleId, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.PUT_OBSERVABILITY_ALERTS_RULES_PARAM,
                List.of(ruleId),
                query,
                body,
                responseType);
    }

    /**
     * Calls the contract route {@code PUT /observability/alerts/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|PUT|/observability/alerts/{param}")
    public <T> @Nullable T putObservabilityAlertsParam(
            String pathParam1, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.PUT_OBSERVABILITY_ALERTS_PARAM, List.of(pathParam1), query, body, responseType);
    }

    /**
     * Calls the contract route {@code PUT /observability/alerts/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T putObservabilityAlertsParam(
            String pathParam1, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.PUT_OBSERVABILITY_ALERTS_PARAM, List.of(pathParam1), query, body, responseType);
    }

    /**
     * Calls the contract route {@code PUT /observability/dashboards/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("observability|PUT|/observability/dashboards/{param}")
    public <T> @Nullable T putObservabilityDashboardsParam(
            String pathParam1, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.PUT_OBSERVABILITY_DASHBOARDS_PARAM,
                List.of(pathParam1),
                query,
                body,
                responseType);
    }

    /**
     * Calls the contract route {@code PUT /observability/dashboards/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T putObservabilityDashboardsParam(
            String pathParam1, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Observability.PUT_OBSERVABILITY_DASHBOARDS_PARAM,
                List.of(pathParam1),
                query,
                body,
                responseType);
    }

    /**
     * Opens the event stream for {@code STREAM /observability/logs/stream}.
     * @param query query supplied to the operation
     * @return a publisher that emits event data
     */
    @SdkOperation("observability|STREAM|/observability/logs/stream")
    public Flow.Publisher<String> streamObservabilityLogsStream(QueryParams query) {
        return streamPublisher(Endpoints.Observability.STREAM_OBSERVABILITY_LOGS_STREAM, List.of(), query);
    }

    /**
     * Opens a blocking event stream for {@code STREAM /observability/logs/stream}.
     * @param query query supplied to the operation
     * @return an iterator that must be closed
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public SseEventIterator streamObservabilityLogsStreamBlocking(QueryParams query)
            throws IOException, InterruptedException {
        return streamEvents(Endpoints.Observability.STREAM_OBSERVABILITY_LOGS_STREAM, List.of(), query);
    }
}
