package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for ontology/rollups. Generated by scripts/generate_endpoints.py. */
public final class OntologyRollupsClient extends ServiceClient {
    OntologyRollupsClient(ApiClient client) {
        super(ApiService.ONTOLOGY, client);
    }

    /** Returns the client for the nested resource.
     * @return the capabilities resource client
     */
    public OntologyRollupsCapabilitiesClient capabilities() {
        return new OntologyRollupsCapabilitiesClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the rollup-results resource client
     */
    public OntologyRollupsRollupResultsClient rollupResults() {
        return new OntologyRollupsRollupResultsClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the rollups resource client
     */
    public OntologyRollupsRollupsClient rollups() {
        return new OntologyRollupsRollupsClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the runs resource client
     */
    public OntologyRollupsRunsClient runs() {
        return new OntologyRollupsRunsClient(client());
    }

    /**
     * Calls the contract route {@code GET /ontology/rollups/health}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ontology|GET|/ontology/rollups/health")
    public <T> @Nullable T health(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Ontology.GET_ONTOLOGY_ROLLUPS_HEALTH, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/rollups/health} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T health(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ontology.GET_ONTOLOGY_ROLLUPS_HEALTH, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/rollups/health} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T health(Class<T> responseType) throws IOException, InterruptedException {
        return health(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/rollups/health} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T health(TypeReference<T> responseType) throws IOException, InterruptedException {
        return health(QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /ontology/rollups/info}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ontology|GET|/ontology/rollups/info")
    public <T> @Nullable T getInfo(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Ontology.GET_ONTOLOGY_ROLLUPS_INFO, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/rollups/info} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getInfo(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ontology.GET_ONTOLOGY_ROLLUPS_INFO, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/rollups/info} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getInfo(Class<T> responseType) throws IOException, InterruptedException {
        return getInfo(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/rollups/info} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getInfo(TypeReference<T> responseType) throws IOException, InterruptedException {
        return getInfo(QueryParams.empty(), responseType);
    }
}
