package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for ontology/objects/object-types. Generated by scripts/generate_endpoints.py. */
public final class OntologyObjectsObjectTypesClient extends ServiceClient {
    OntologyObjectsObjectTypesClient(ApiClient client) {
        super(ApiService.ONTOLOGY, client);
    }

    /**
     * Calls the contract route {@code DELETE /ontology/objects/object-types/{param}}.
     * @param <T> decoded response type
     * @param objectTypeId objectTypeId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ontology|DELETE|/ontology/objects/object-types/{param}")
    public <T> @Nullable T delete(String objectTypeId, QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Ontology.DELETE_ONTOLOGY_OBJECTS_OBJECT_TYPES_PARAM, List.of(objectTypeId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code DELETE /ontology/objects/object-types/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param objectTypeId objectTypeId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T delete(String objectTypeId, QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Ontology.DELETE_ONTOLOGY_OBJECTS_OBJECT_TYPES_PARAM, List.of(objectTypeId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code DELETE /ontology/objects/object-types/{param}} without query parameters.
     * @param <T> decoded response type
     * @param objectTypeId objectTypeId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T delete(String objectTypeId, Class<T> responseType) throws IOException, InterruptedException {
        return delete(objectTypeId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code DELETE /ontology/objects/object-types/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param objectTypeId objectTypeId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T delete(String objectTypeId, TypeReference<T> responseType) throws IOException, InterruptedException {
        return delete(objectTypeId, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /ontology/objects/object-types}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ontology|GET|/ontology/objects/object-types")
    public <T> @Nullable T list(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Ontology.GET_ONTOLOGY_OBJECTS_OBJECT_TYPES, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/objects/object-types} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Ontology.GET_ONTOLOGY_OBJECTS_OBJECT_TYPES, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/objects/object-types} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(Class<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/objects/object-types} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(TypeReference<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /ontology/objects/object-types/{param}}.
     * @param <T> decoded response type
     * @param objectTypeId objectTypeId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ontology|GET|/ontology/objects/object-types/{param}")
    public <T> @Nullable T get(String objectTypeId, QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Ontology.GET_ONTOLOGY_OBJECTS_OBJECT_TYPES_PARAM, List.of(objectTypeId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/objects/object-types/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param objectTypeId objectTypeId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String objectTypeId, QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Ontology.GET_ONTOLOGY_OBJECTS_OBJECT_TYPES_PARAM, List.of(objectTypeId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/objects/object-types/{param}} without query parameters.
     * @param <T> decoded response type
     * @param objectTypeId objectTypeId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String objectTypeId, Class<T> responseType) throws IOException, InterruptedException {
        return get(objectTypeId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/objects/object-types/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param objectTypeId objectTypeId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String objectTypeId, TypeReference<T> responseType) throws IOException, InterruptedException {
        return get(objectTypeId, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code PUT /ontology/objects/object-types/{param}}.
     * @param <T> decoded response type
     * @param objectTypeId objectTypeId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ontology|PUT|/ontology/objects/object-types/{param}")
    public <T> @Nullable T update(String objectTypeId, QueryParams query, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Ontology.PUT_ONTOLOGY_OBJECTS_OBJECT_TYPES_PARAM, List.of(objectTypeId), query, body, responseType);
    }
    /**
     * Calls the contract route {@code PUT /ontology/objects/object-types/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param objectTypeId objectTypeId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T update(String objectTypeId, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Ontology.PUT_ONTOLOGY_OBJECTS_OBJECT_TYPES_PARAM, List.of(objectTypeId), query, body, responseType);
    }
    /**
     * Calls the contract route {@code PUT /ontology/objects/object-types/{param}} without query parameters.
     * @param <T> decoded response type
     * @param objectTypeId objectTypeId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T update(String objectTypeId, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return update(objectTypeId, QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code PUT /ontology/objects/object-types/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param objectTypeId objectTypeId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T update(String objectTypeId, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return update(objectTypeId, QueryParams.empty(), body, responseType);
    }

}
