package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for ontology/rollouts/rollouts. Generated by scripts/generate_endpoints.py. */
public final class OntologyRolloutsRolloutsClient extends ServiceClient {
    OntologyRolloutsRolloutsClient(ApiClient client) {
        super(ApiService.ONTOLOGY, client);
    }

    /**
     * Calls the contract route {@code DELETE /ontology/rollouts/rollouts/{param}}.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ontology|DELETE|/ontology/rollouts/rollouts/{param}")
    public <T> @Nullable T delete(String rolloutId, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Ontology.DELETE_ONTOLOGY_ROLLOUTS_ROLLOUTS_PARAM,
                List.of(rolloutId),
                query,
                null,
                responseType);
    }
    /**
     * Calls the contract route {@code DELETE /ontology/rollouts/rollouts/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T delete(String rolloutId, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Ontology.DELETE_ONTOLOGY_ROLLOUTS_ROLLOUTS_PARAM,
                List.of(rolloutId),
                query,
                null,
                responseType);
    }
    /**
     * Calls the contract route {@code DELETE /ontology/rollouts/rollouts/{param}} without query parameters.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T delete(String rolloutId, Class<T> responseType) throws IOException, InterruptedException {
        return delete(rolloutId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code DELETE /ontology/rollouts/rollouts/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T delete(String rolloutId, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return delete(rolloutId, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /ontology/rollouts/rollouts}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ontology|GET|/ontology/rollouts/rollouts")
    public <T> @Nullable T list(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Ontology.GET_ONTOLOGY_ROLLOUTS_ROLLOUTS, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/rollouts/rollouts} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ontology.GET_ONTOLOGY_ROLLOUTS_ROLLOUTS, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/rollouts/rollouts} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(Class<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/rollouts/rollouts} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(TypeReference<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /ontology/rollouts/rollouts/{param}}.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ontology|GET|/ontology/rollouts/rollouts/{param}")
    public <T> @Nullable T get(String rolloutId, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Ontology.GET_ONTOLOGY_ROLLOUTS_ROLLOUTS_PARAM, List.of(rolloutId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/rollouts/rollouts/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String rolloutId, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Ontology.GET_ONTOLOGY_ROLLOUTS_ROLLOUTS_PARAM, List.of(rolloutId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/rollouts/rollouts/{param}} without query parameters.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String rolloutId, Class<T> responseType) throws IOException, InterruptedException {
        return get(rolloutId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/rollouts/rollouts/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String rolloutId, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return get(rolloutId, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /ontology/rollouts/rollouts/{param}/status}.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ontology|GET|/ontology/rollouts/rollouts/{param}/status")
    public <T> @Nullable T status(String rolloutId, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Ontology.GET_ONTOLOGY_ROLLOUTS_ROLLOUTS_PARAM_STATUS,
                List.of(rolloutId),
                query,
                null,
                responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/rollouts/rollouts/{param}/status} using a generic response type.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T status(String rolloutId, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Ontology.GET_ONTOLOGY_ROLLOUTS_ROLLOUTS_PARAM_STATUS,
                List.of(rolloutId),
                query,
                null,
                responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/rollouts/rollouts/{param}/status} without query parameters.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T status(String rolloutId, Class<T> responseType) throws IOException, InterruptedException {
        return status(rolloutId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/rollouts/rollouts/{param}/status} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T status(String rolloutId, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return status(rolloutId, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code POST /ontology/rollouts/rollouts}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ontology|POST|/ontology/rollouts/rollouts")
    public <T> @Nullable T create(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ontology.POST_ONTOLOGY_ROLLOUTS_ROLLOUTS, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /ontology/rollouts/rollouts} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ontology.POST_ONTOLOGY_ROLLOUTS_ROLLOUTS, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /ontology/rollouts/rollouts} without query parameters.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(@Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return create(QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /ontology/rollouts/rollouts} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(@Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return create(QueryParams.empty(), body, responseType);
    }

    /**
     * Calls the contract route {@code POST /ontology/rollouts/rollouts/{param}/pause}.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ontology|POST|/ontology/rollouts/rollouts/{param}/pause")
    public <T> @Nullable T pause(String rolloutId, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Ontology.POST_ONTOLOGY_ROLLOUTS_ROLLOUTS_PARAM_PAUSE,
                List.of(rolloutId),
                query,
                body,
                responseType);
    }
    /**
     * Calls the contract route {@code POST /ontology/rollouts/rollouts/{param}/pause} using a generic response type.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T pause(
            String rolloutId, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Ontology.POST_ONTOLOGY_ROLLOUTS_ROLLOUTS_PARAM_PAUSE,
                List.of(rolloutId),
                query,
                body,
                responseType);
    }
    /**
     * Calls the contract route {@code POST /ontology/rollouts/rollouts/{param}/pause} without query parameters.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T pause(String rolloutId, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return pause(rolloutId, QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /ontology/rollouts/rollouts/{param}/pause} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T pause(String rolloutId, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return pause(rolloutId, QueryParams.empty(), body, responseType);
    }

    /**
     * Calls the contract route {@code POST /ontology/rollouts/rollouts/{param}/resume}.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ontology|POST|/ontology/rollouts/rollouts/{param}/resume")
    public <T> @Nullable T resume(String rolloutId, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Ontology.POST_ONTOLOGY_ROLLOUTS_ROLLOUTS_PARAM_RESUME,
                List.of(rolloutId),
                query,
                body,
                responseType);
    }
    /**
     * Calls the contract route {@code POST /ontology/rollouts/rollouts/{param}/resume} using a generic response type.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T resume(
            String rolloutId, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Ontology.POST_ONTOLOGY_ROLLOUTS_ROLLOUTS_PARAM_RESUME,
                List.of(rolloutId),
                query,
                body,
                responseType);
    }
    /**
     * Calls the contract route {@code POST /ontology/rollouts/rollouts/{param}/resume} without query parameters.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T resume(String rolloutId, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return resume(rolloutId, QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /ontology/rollouts/rollouts/{param}/resume} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T resume(String rolloutId, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return resume(rolloutId, QueryParams.empty(), body, responseType);
    }

    /**
     * Calls the contract route {@code POST /ontology/rollouts/rollouts/{param}/rollback}.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ontology|POST|/ontology/rollouts/rollouts/{param}/rollback")
    public <T> @Nullable T rollback(String rolloutId, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Ontology.POST_ONTOLOGY_ROLLOUTS_ROLLOUTS_PARAM_ROLLBACK,
                List.of(rolloutId),
                query,
                body,
                responseType);
    }
    /**
     * Calls the contract route {@code POST /ontology/rollouts/rollouts/{param}/rollback} using a generic response type.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T rollback(
            String rolloutId, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Ontology.POST_ONTOLOGY_ROLLOUTS_ROLLOUTS_PARAM_ROLLBACK,
                List.of(rolloutId),
                query,
                body,
                responseType);
    }
    /**
     * Calls the contract route {@code POST /ontology/rollouts/rollouts/{param}/rollback} without query parameters.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T rollback(String rolloutId, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return rollback(rolloutId, QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /ontology/rollouts/rollouts/{param}/rollback} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T rollback(String rolloutId, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return rollback(rolloutId, QueryParams.empty(), body, responseType);
    }

    /**
     * Calls the contract route {@code POST /ontology/rollouts/rollouts/{param}/start}.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ontology|POST|/ontology/rollouts/rollouts/{param}/start")
    public <T> @Nullable T createStart(
            String rolloutId, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Ontology.POST_ONTOLOGY_ROLLOUTS_ROLLOUTS_PARAM_START,
                List.of(rolloutId),
                query,
                body,
                responseType);
    }
    /**
     * Calls the contract route {@code POST /ontology/rollouts/rollouts/{param}/start} using a generic response type.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T createStart(
            String rolloutId, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Ontology.POST_ONTOLOGY_ROLLOUTS_ROLLOUTS_PARAM_START,
                List.of(rolloutId),
                query,
                body,
                responseType);
    }
    /**
     * Calls the contract route {@code POST /ontology/rollouts/rollouts/{param}/start} without query parameters.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T createStart(String rolloutId, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return createStart(rolloutId, QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /ontology/rollouts/rollouts/{param}/start} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T createStart(String rolloutId, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return createStart(rolloutId, QueryParams.empty(), body, responseType);
    }

    /**
     * Calls the contract route {@code PUT /ontology/rollouts/rollouts/{param}}.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ontology|PUT|/ontology/rollouts/rollouts/{param}")
    public <T> @Nullable T update(String rolloutId, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Ontology.PUT_ONTOLOGY_ROLLOUTS_ROLLOUTS_PARAM, List.of(rolloutId), query, body, responseType);
    }
    /**
     * Calls the contract route {@code PUT /ontology/rollouts/rollouts/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T update(
            String rolloutId, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Ontology.PUT_ONTOLOGY_ROLLOUTS_ROLLOUTS_PARAM, List.of(rolloutId), query, body, responseType);
    }
    /**
     * Calls the contract route {@code PUT /ontology/rollouts/rollouts/{param}} without query parameters.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T update(String rolloutId, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return update(rolloutId, QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code PUT /ontology/rollouts/rollouts/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param rolloutId rolloutId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T update(String rolloutId, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return update(rolloutId, QueryParams.empty(), body, responseType);
    }
}
