package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for ontology/objects. Generated by scripts/generate_endpoints.py. */
public final class OntologyObjectsClient extends ServiceClient {
    OntologyObjectsClient(ApiClient client) {
        super(ApiService.ONTOLOGY, client);
    }

    /** Returns the client for the nested resource.
     * @return the capabilities resource client
     */
    public OntologyObjectsCapabilitiesClient capabilities() {
        return new OntologyObjectsCapabilitiesClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the object-types resource client
     */
    public OntologyObjectsObjectTypesClient objectTypes() {
        return new OntologyObjectsObjectTypesClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the objects resource client
     */
    public OntologyObjectsObjectsClient objects() {
        return new OntologyObjectsObjectsClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the runs resource client
     */
    public OntologyObjectsRunsClient runs() {
        return new OntologyObjectsRunsClient(client());
    }

    /**
     * Calls the contract route {@code GET /ontology/objects/health}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ontology|GET|/ontology/objects/health")
    public <T> @Nullable T health(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Ontology.GET_ONTOLOGY_OBJECTS_HEALTH, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/objects/health} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T health(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ontology.GET_ONTOLOGY_OBJECTS_HEALTH, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/objects/health} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T health(Class<T> responseType) throws IOException, InterruptedException {
        return health(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/objects/health} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T health(TypeReference<T> responseType) throws IOException, InterruptedException {
        return health(QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /ontology/objects/info}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ontology|GET|/ontology/objects/info")
    public <T> @Nullable T getInfo(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Ontology.GET_ONTOLOGY_OBJECTS_INFO, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/objects/info} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getInfo(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Ontology.GET_ONTOLOGY_OBJECTS_INFO, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/objects/info} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getInfo(Class<T> responseType) throws IOException, InterruptedException {
        return getInfo(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/objects/info} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getInfo(TypeReference<T> responseType) throws IOException, InterruptedException {
        return getInfo(QueryParams.empty(), responseType);
    }
}
