package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for ontology/relationships/relationship-types. Generated by scripts/generate_endpoints.py. */
public final class OntologyRelationshipsRelationshipTypesClient extends ServiceClient {
    OntologyRelationshipsRelationshipTypesClient(ApiClient client) {
        super(ApiService.ONTOLOGY, client);
    }

    /**
     * Calls the contract route {@code DELETE /ontology/relationships/relationship-types/{param}}.
     * @param <T> decoded response type
     * @param relationshipTypeId relationshipTypeId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ontology|DELETE|/ontology/relationships/relationship-types/{param}")
    public <T> @Nullable T delete(String relationshipTypeId, QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Ontology.DELETE_ONTOLOGY_RELATIONSHIPS_RELATIONSHIP_TYPES_PARAM, List.of(relationshipTypeId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code DELETE /ontology/relationships/relationship-types/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param relationshipTypeId relationshipTypeId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T delete(String relationshipTypeId, QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Ontology.DELETE_ONTOLOGY_RELATIONSHIPS_RELATIONSHIP_TYPES_PARAM, List.of(relationshipTypeId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code DELETE /ontology/relationships/relationship-types/{param}} without query parameters.
     * @param <T> decoded response type
     * @param relationshipTypeId relationshipTypeId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T delete(String relationshipTypeId, Class<T> responseType) throws IOException, InterruptedException {
        return delete(relationshipTypeId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code DELETE /ontology/relationships/relationship-types/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param relationshipTypeId relationshipTypeId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T delete(String relationshipTypeId, TypeReference<T> responseType) throws IOException, InterruptedException {
        return delete(relationshipTypeId, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /ontology/relationships/relationship-types}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ontology|GET|/ontology/relationships/relationship-types")
    public <T> @Nullable T list(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Ontology.GET_ONTOLOGY_RELATIONSHIPS_RELATIONSHIP_TYPES, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/relationships/relationship-types} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Ontology.GET_ONTOLOGY_RELATIONSHIPS_RELATIONSHIP_TYPES, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/relationships/relationship-types} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(Class<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/relationships/relationship-types} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(TypeReference<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }

}
