package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for ontology/rollouts. Generated by scripts/generate_endpoints.py. */
public final class OntologyRolloutsClient extends ServiceClient {
    OntologyRolloutsClient(ApiClient client) {
        super(ApiService.ONTOLOGY, client);
    }

    /** Returns the client for the nested resource.
     * @return the capabilities resource client
     */
    public OntologyRolloutsCapabilitiesClient capabilities() {
        return new OntologyRolloutsCapabilitiesClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the rollouts resource client
     */
    public OntologyRolloutsRolloutsClient rollouts() {
        return new OntologyRolloutsRolloutsClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the runs resource client
     */
    public OntologyRolloutsRunsClient runs() {
        return new OntologyRolloutsRunsClient(client());
    }

    /**
     * Calls the contract route {@code GET /ontology/rollouts/health}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ontology|GET|/ontology/rollouts/health")
    public <T> @Nullable T health(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Ontology.GET_ONTOLOGY_ROLLOUTS_HEALTH, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/rollouts/health} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T health(QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Ontology.GET_ONTOLOGY_ROLLOUTS_HEALTH, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/rollouts/health} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T health(Class<T> responseType) throws IOException, InterruptedException {
        return health(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/rollouts/health} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T health(TypeReference<T> responseType) throws IOException, InterruptedException {
        return health(QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /ontology/rollouts/info}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ontology|GET|/ontology/rollouts/info")
    public <T> @Nullable T getInfo(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Ontology.GET_ONTOLOGY_ROLLOUTS_INFO, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/rollouts/info} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getInfo(QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Ontology.GET_ONTOLOGY_ROLLOUTS_INFO, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/rollouts/info} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getInfo(Class<T> responseType) throws IOException, InterruptedException {
        return getInfo(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /ontology/rollouts/info} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getInfo(TypeReference<T> responseType) throws IOException, InterruptedException {
        return getInfo(QueryParams.empty(), responseType);
    }

}
