package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for ontology/validation/payloads. Generated by scripts/generate_endpoints.py. */
public final class OntologyValidationPayloadsClient extends ServiceClient {
    OntologyValidationPayloadsClient(ApiClient client) {
        super(ApiService.ONTOLOGY, client);
    }

    /**
     * Calls the contract route {@code POST /ontology/validation/payloads/validate}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("ontology|POST|/ontology/validation/payloads/validate")
    public <T> @Nullable T validate(QueryParams query, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Ontology.POST_ONTOLOGY_VALIDATION_PAYLOADS_VALIDATE, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /ontology/validation/payloads/validate} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T validate(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Ontology.POST_ONTOLOGY_VALIDATION_PAYLOADS_VALIDATE, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /ontology/validation/payloads/validate} without query parameters.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T validate(@Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return validate(QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /ontology/validation/payloads/validate} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T validate(@Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return validate(QueryParams.empty(), body, responseType);
    }

}
