package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for pipelines/data. Generated by scripts/generate_endpoints.py. */
public final class PipelinesDataClient extends ServiceClient {
    PipelinesDataClient(ApiClient client) {
        super(ApiService.PIPELINES, client);
    }

    /** Returns the client for the nested resource.
     * @return the pipelines resource client
     */
    public PipelinesDataPipelinesClient pipelines() {
        return new PipelinesDataPipelinesClient(client());
    }

}
