package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for pipelines/data/pipelines/capabilities. Generated by scripts/generate_endpoints.py. */
public final class PipelinesDataPipelinesCapabilitiesClient extends ServiceClient {
    PipelinesDataPipelinesCapabilitiesClient(ApiClient client) {
        super(ApiService.PIPELINES, client);
    }

    /**
     * Calls the contract route {@code GET /data/pipelines/capabilities}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("pipelines|GET|/data/pipelines/capabilities")
    public <T> @Nullable T list(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Pipelines.GET_DATA_PIPELINES_CAPABILITIES, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/pipelines/capabilities} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Pipelines.GET_DATA_PIPELINES_CAPABILITIES, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/pipelines/capabilities} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(Class<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /data/pipelines/capabilities} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(TypeReference<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }

}
