package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;
import java.util.concurrent.Flow;

/** Contract operations for pipelines/data/pipelines/pipeline-runs. Generated by scripts/generate_endpoints.py. */
public final class PipelinesDataPipelinesPipelineRunsClient extends ServiceClient {
    PipelinesDataPipelinesPipelineRunsClient(ApiClient client) {
        super(ApiService.PIPELINES, client);
    }

    /**
     * Calls the contract route {@code GET /data/pipelines/pipeline-runs}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("pipelines|GET|/data/pipelines/pipeline-runs")
    public <T> @Nullable T list(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Pipelines.GET_DATA_PIPELINES_PIPELINE_RUNS, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/pipelines/pipeline-runs} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Pipelines.GET_DATA_PIPELINES_PIPELINE_RUNS, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/pipelines/pipeline-runs} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(Class<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /data/pipelines/pipeline-runs} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(TypeReference<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /data/pipelines/pipeline-runs/{param}}.
     * @param <T> decoded response type
     * @param pipelineRunId pipelineRunId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("pipelines|GET|/data/pipelines/pipeline-runs/{param}")
    public <T> @Nullable T get(String pipelineRunId, QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Pipelines.GET_DATA_PIPELINES_PIPELINE_RUNS_PARAM, List.of(pipelineRunId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/pipelines/pipeline-runs/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param pipelineRunId pipelineRunId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String pipelineRunId, QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Pipelines.GET_DATA_PIPELINES_PIPELINE_RUNS_PARAM, List.of(pipelineRunId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /data/pipelines/pipeline-runs/{param}} without query parameters.
     * @param <T> decoded response type
     * @param pipelineRunId pipelineRunId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String pipelineRunId, Class<T> responseType) throws IOException, InterruptedException {
        return get(pipelineRunId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /data/pipelines/pipeline-runs/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param pipelineRunId pipelineRunId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String pipelineRunId, TypeReference<T> responseType) throws IOException, InterruptedException {
        return get(pipelineRunId, QueryParams.empty(), responseType);
    }

    /**
     * Opens the event stream for {@code STREAM /data/pipelines/pipeline-runs/{param}}.
     * @param pipelineRunId pipelineRunId supplied to the operation
     * @param query query supplied to the operation
     * @return a publisher that emits event data
     */
    @SdkOperation("pipelines|STREAM|/data/pipelines/pipeline-runs/{param}")
    public Flow.Publisher<String> get2(String pipelineRunId, QueryParams query) {
        return streamPublisher(Endpoints.Pipelines.STREAM_DATA_PIPELINES_PIPELINE_RUNS_PARAM, List.of(pipelineRunId), query);
    }
    /**
     * Opens a blocking event stream for {@code STREAM /data/pipelines/pipeline-runs/{param}}.
     * @param pipelineRunId pipelineRunId supplied to the operation
     * @param query query supplied to the operation
     * @return an iterator that must be closed
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public SseEventIterator get2Blocking(String pipelineRunId, QueryParams query) throws IOException, InterruptedException {
        return streamEvents(Endpoints.Pipelines.STREAM_DATA_PIPELINES_PIPELINE_RUNS_PARAM, List.of(pipelineRunId), query);
    }
    /**
     * Opens the event stream for {@code STREAM /data/pipelines/pipeline-runs/{param}} with no query parameters.
     * @param pipelineRunId pipelineRunId supplied to the operation
     * @return a publisher that emits event data
     */
    public Flow.Publisher<String> get2(String pipelineRunId) {
        return get2(pipelineRunId, QueryParams.empty());
    }
    /**
     * Opens a blocking event stream for {@code STREAM /data/pipelines/pipeline-runs/{param}} with no query parameters.
     * @param pipelineRunId pipelineRunId supplied to the operation
     * @return an iterator that must be closed
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public SseEventIterator get2Blocking(String pipelineRunId) throws IOException, InterruptedException {
        return get2Blocking(pipelineRunId, QueryParams.empty());
    }

}
