package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import java.util.concurrent.Flow;
import org.jspecify.annotations.Nullable;

/** Named contract operations for the pipelines service. Generated by scripts/generate_endpoints.py. */
public final class PipelinesClient extends ServiceClient {
    PipelinesClient(ApiClient client) {
        super(ApiService.PIPELINES, client);
    }

    /**
     * Calls the contract route {@code GET /data/pipelines/capabilities}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("pipelines|GET|/data/pipelines/capabilities")
    public <T> @Nullable T getDataPipelinesCapabilities(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Pipelines.GET_DATA_PIPELINES_CAPABILITIES, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /data/pipelines/capabilities}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getDataPipelinesCapabilities(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Pipelines.GET_DATA_PIPELINES_CAPABILITIES, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /data/pipelines/health}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("pipelines|GET|/data/pipelines/health")
    public <T> @Nullable T getDataPipelinesHealth(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Pipelines.GET_DATA_PIPELINES_HEALTH, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /data/pipelines/health}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getDataPipelinesHealth(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Pipelines.GET_DATA_PIPELINES_HEALTH, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /data/pipelines/info}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("pipelines|GET|/data/pipelines/info")
    public <T> @Nullable T getDataPipelinesInfo(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Pipelines.GET_DATA_PIPELINES_INFO, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /data/pipelines/info}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getDataPipelinesInfo(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Pipelines.GET_DATA_PIPELINES_INFO, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /data/pipelines/pipeline-runs}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("pipelines|GET|/data/pipelines/pipeline-runs")
    public <T> @Nullable T getDataPipelinesPipelineRuns(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Pipelines.GET_DATA_PIPELINES_PIPELINE_RUNS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /data/pipelines/pipeline-runs}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getDataPipelinesPipelineRuns(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Pipelines.GET_DATA_PIPELINES_PIPELINE_RUNS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /data/pipelines/pipeline-runs/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("pipelines|GET|/data/pipelines/pipeline-runs/{param}")
    public <T> @Nullable T getDataPipelinesPipelineRunsParam(
            String pathParam1, QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(
                Endpoints.Pipelines.GET_DATA_PIPELINES_PIPELINE_RUNS_PARAM,
                List.of(pathParam1),
                query,
                null,
                responseType);
    }

    /**
     * Calls the contract route {@code GET /data/pipelines/pipeline-runs/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getDataPipelinesPipelineRunsParam(
            String pathParam1, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Pipelines.GET_DATA_PIPELINES_PIPELINE_RUNS_PARAM,
                List.of(pathParam1),
                query,
                null,
                responseType);
    }

    /**
     * Calls the contract route {@code GET /data/pipelines/pipelines}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("pipelines|GET|/data/pipelines/pipelines")
    public <T> @Nullable T getDataPipelinesPipelines(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Pipelines.GET_DATA_PIPELINES_PIPELINES, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /data/pipelines/pipelines}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getDataPipelinesPipelines(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Pipelines.GET_DATA_PIPELINES_PIPELINES, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /data/pipelines/pipelines/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("pipelines|GET|/data/pipelines/pipelines/{param}")
    public <T> @Nullable T getDataPipelinesPipelinesParam(String pathParam1, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Pipelines.GET_DATA_PIPELINES_PIPELINES_PARAM, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /data/pipelines/pipelines/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getDataPipelinesPipelinesParam(
            String pathParam1, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Pipelines.GET_DATA_PIPELINES_PIPELINES_PARAM, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /data/pipelines/runs}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("pipelines|GET|/data/pipelines/runs")
    public <T> @Nullable T getDataPipelinesRuns(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Pipelines.GET_DATA_PIPELINES_RUNS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /data/pipelines/runs}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getDataPipelinesRuns(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Pipelines.GET_DATA_PIPELINES_RUNS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code POST /data/pipelines/pipelines}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("pipelines|POST|/data/pipelines/pipelines")
    public <T> @Nullable T postDataPipelinesPipelines(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Pipelines.POST_DATA_PIPELINES_PIPELINES, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /data/pipelines/pipelines}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postDataPipelinesPipelines(
            QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Pipelines.POST_DATA_PIPELINES_PIPELINES, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /data/pipelines/runs}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("pipelines|POST|/data/pipelines/runs")
    public <T> @Nullable T postDataPipelinesRuns(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Pipelines.POST_DATA_PIPELINES_RUNS, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /data/pipelines/runs}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postDataPipelinesRuns(
            QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Pipelines.POST_DATA_PIPELINES_RUNS, List.of(), query, body, responseType);
    }

    /**
     * Opens the event stream for {@code STREAM /data/pipelines/pipeline-runs/{param}}.
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @return a publisher that emits event data
     */
    @SdkOperation("pipelines|STREAM|/data/pipelines/pipeline-runs/{param}")
    public Flow.Publisher<String> streamDataPipelinesPipelineRunsParam(String pathParam1, QueryParams query) {
        return streamPublisher(
                Endpoints.Pipelines.STREAM_DATA_PIPELINES_PIPELINE_RUNS_PARAM, List.of(pathParam1), query);
    }

    /**
     * Opens a blocking event stream for {@code STREAM /data/pipelines/pipeline-runs/{param}}.
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @return an iterator that must be closed
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public SseEventIterator streamDataPipelinesPipelineRunsParamBlocking(String pathParam1, QueryParams query)
            throws IOException, InterruptedException {
        return streamEvents(Endpoints.Pipelines.STREAM_DATA_PIPELINES_PIPELINE_RUNS_PARAM, List.of(pathParam1), query);
    }
}
