package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Named contract operations for the providers service. Generated by scripts/generate_endpoints.py. */
public final class ProvidersClient extends ServiceClient {
    ProvidersClient(ApiClient client) {
        super(ApiService.PROVIDERS, client);
    }

    /**
     * Calls the contract route {@code GET /providers/{param}}.
     * @param <T> decoded response type
     * @param providerSlug providerSlug supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("providers|GET|/providers/{param}")
    public <T> @Nullable T getProvidersProviderSlug(String providerSlug, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Providers.GET_PROVIDERS_PARAM, List.of(providerSlug), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /providers/{param}}.
     * @param <T> decoded response type
     * @param providerSlug providerSlug supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getProvidersProviderSlug(
            String providerSlug, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Providers.GET_PROVIDERS_PARAM, List.of(providerSlug), query, null, responseType);
    }
}
