package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Named contract operations for the sandbox service. Generated by scripts/generate_endpoints.py. */
public final class SandboxClient extends ServiceClient {
    SandboxClient(ApiClient client) {
        super(ApiService.SANDBOX, client);
    }

    /**
     * Calls the contract route {@code GET /sandbox/languages}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("sandbox|GET|/sandbox/languages")
    public <T> @Nullable T getSandboxLanguages(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Sandbox.GET_SANDBOX_LANGUAGES, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /sandbox/languages}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getSandboxLanguages(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Sandbox.GET_SANDBOX_LANGUAGES, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code POST /sandbox/self-test}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("sandbox|POST|/sandbox/self-test")
    public <T> @Nullable T postSandboxSelfTest(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Sandbox.POST_SANDBOX_SELF_TEST, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /sandbox/self-test}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postSandboxSelfTest(
            QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Sandbox.POST_SANDBOX_SELF_TEST, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /sandbox/submit}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("sandbox|POST|/sandbox/submit")
    public <T> @Nullable T postSandboxSubmit(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Sandbox.POST_SANDBOX_SUBMIT, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /sandbox/submit}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postSandboxSubmit(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Sandbox.POST_SANDBOX_SUBMIT, List.of(), query, body, responseType);
    }
}
