package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for schedules/workflows. Generated by scripts/generate_endpoints.py. */
public final class SchedulesWorkflowsClient extends ServiceClient {
    SchedulesWorkflowsClient(ApiClient client) {
        super(ApiService.SCHEDULES, client);
    }

    /** Returns the client for the nested resource.
     * @return the cron resource client
     */
    public SchedulesWorkflowsCronClient cron() {
        return new SchedulesWorkflowsCronClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the schedules resource client
     */
    public SchedulesWorkflowsSchedulesClient schedules() {
        return new SchedulesWorkflowsSchedulesClient(client());
    }

}
