package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for schedules. Generated by scripts/generate_endpoints.py. */
public final class SchedulesClient extends ServiceClient {
    SchedulesClient(ApiClient client) {
        super(ApiService.SCHEDULES, client);
    }

    /** Returns the client for the nested resource.
     * @return the workflows resource client
     */
    public SchedulesWorkflowsClient workflows() {
        return new SchedulesWorkflowsClient(client());
    }

}
