package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Named contract operations for the webhook-endpoints service. Generated by scripts/generate_endpoints.py. */
public final class WebhookEndpointsClient extends ServiceClient {
    WebhookEndpointsClient(ApiClient client) {
        super(ApiService.WEBHOOK_ENDPOINTS, client);
    }

    /**
     * Calls the contract route {@code DELETE /webhook-endpoints/{param}}.
     * @param <T> decoded response type
     * @param id id supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("webhook-endpoints|DELETE|/webhook-endpoints/{param}")
    public <T> @Nullable T deleteWebhookEndpointsId(String id, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.WebhookEndpoints.DELETE_WEBHOOK_ENDPOINTS_PARAM, List.of(id), query, null, responseType);
    }

    /**
     * Calls the contract route {@code DELETE /webhook-endpoints/{param}}.
     * @param <T> decoded response type
     * @param id id supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T deleteWebhookEndpointsId(String id, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.WebhookEndpoints.DELETE_WEBHOOK_ENDPOINTS_PARAM, List.of(id), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /webhook-endpoints}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("webhook-endpoints|GET|/webhook-endpoints")
    public <T> @Nullable T getWebhookEndpoints(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.WebhookEndpoints.GET_WEBHOOK_ENDPOINTS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /webhook-endpoints}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getWebhookEndpoints(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.WebhookEndpoints.GET_WEBHOOK_ENDPOINTS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /webhook-endpoints/{param}}.
     * @param <T> decoded response type
     * @param id id supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("webhook-endpoints|GET|/webhook-endpoints/{param}")
    public <T> @Nullable T getWebhookEndpointsId(String id, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.WebhookEndpoints.GET_WEBHOOK_ENDPOINTS_PARAM, List.of(id), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /webhook-endpoints/{param}}.
     * @param <T> decoded response type
     * @param id id supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getWebhookEndpointsId(String id, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.WebhookEndpoints.GET_WEBHOOK_ENDPOINTS_PARAM, List.of(id), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /webhook-endpoints/{param}/deliveries}.
     * @param <T> decoded response type
     * @param id id supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("webhook-endpoints|GET|/webhook-endpoints/{param}/deliveries")
    public <T> @Nullable T getWebhookEndpointsIdDeliveries(String id, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.WebhookEndpoints.GET_WEBHOOK_ENDPOINTS_PARAM_DELIVERIES,
                List.of(id),
                query,
                null,
                responseType);
    }

    /**
     * Calls the contract route {@code GET /webhook-endpoints/{param}/deliveries}.
     * @param <T> decoded response type
     * @param id id supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getWebhookEndpointsIdDeliveries(String id, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.WebhookEndpoints.GET_WEBHOOK_ENDPOINTS_PARAM_DELIVERIES,
                List.of(id),
                query,
                null,
                responseType);
    }

    /**
     * Calls the contract route {@code PATCH /webhook-endpoints/{param}}.
     * @param <T> decoded response type
     * @param id id supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("webhook-endpoints|PATCH|/webhook-endpoints/{param}")
    public <T> @Nullable T patchWebhookEndpointsId(
            String id, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.WebhookEndpoints.PATCH_WEBHOOK_ENDPOINTS_PARAM, List.of(id), query, body, responseType);
    }

    /**
     * Calls the contract route {@code PATCH /webhook-endpoints/{param}}.
     * @param <T> decoded response type
     * @param id id supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T patchWebhookEndpointsId(
            String id, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.WebhookEndpoints.PATCH_WEBHOOK_ENDPOINTS_PARAM, List.of(id), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /webhook-endpoints}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("webhook-endpoints|POST|/webhook-endpoints")
    public <T> @Nullable T postWebhookEndpoints(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.WebhookEndpoints.POST_WEBHOOK_ENDPOINTS, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /webhook-endpoints}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postWebhookEndpoints(
            QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.WebhookEndpoints.POST_WEBHOOK_ENDPOINTS, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /webhook-endpoints/{param}/rotate-secret}.
     * @param <T> decoded response type
     * @param id id supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("webhook-endpoints|POST|/webhook-endpoints/{param}/rotate-secret")
    public <T> @Nullable T postWebhookEndpointsIdRotateSecret(
            String id, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.WebhookEndpoints.POST_WEBHOOK_ENDPOINTS_PARAM_ROTATE_SECRET,
                List.of(id),
                query,
                body,
                responseType);
    }

    /**
     * Calls the contract route {@code POST /webhook-endpoints/{param}/rotate-secret}.
     * @param <T> decoded response type
     * @param id id supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postWebhookEndpointsIdRotateSecret(
            String id, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.WebhookEndpoints.POST_WEBHOOK_ENDPOINTS_PARAM_ROTATE_SECRET,
                List.of(id),
                query,
                body,
                responseType);
    }
}
