package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for webhooks/deliveries. Generated by scripts/generate_endpoints.py. */
public final class WebhooksDeliveriesClient extends ServiceClient {
    WebhooksDeliveriesClient(ApiClient client) {
        super(ApiService.WEBHOOKS, client);
    }

    /**
     * Calls the contract route {@code GET /webhooks/deliveries}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("webhooks|GET|/webhooks/deliveries")
    public <T> @Nullable T list(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Webhooks.GET_WEBHOOKS_DELIVERIES, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /webhooks/deliveries} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Webhooks.GET_WEBHOOKS_DELIVERIES, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /webhooks/deliveries} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(Class<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /webhooks/deliveries} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(TypeReference<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /webhooks/deliveries/{param}}.
     * @param <T> decoded response type
     * @param deliveryId deliveryId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("webhooks|GET|/webhooks/deliveries/{param}")
    public <T> @Nullable T get(String deliveryId, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Webhooks.GET_WEBHOOKS_DELIVERIES_PARAM, List.of(deliveryId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /webhooks/deliveries/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param deliveryId deliveryId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String deliveryId, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Webhooks.GET_WEBHOOKS_DELIVERIES_PARAM, List.of(deliveryId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /webhooks/deliveries/{param}} without query parameters.
     * @param <T> decoded response type
     * @param deliveryId deliveryId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String deliveryId, Class<T> responseType) throws IOException, InterruptedException {
        return get(deliveryId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /webhooks/deliveries/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param deliveryId deliveryId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String deliveryId, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return get(deliveryId, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code POST /webhooks/deliveries/{param}/retry}.
     * @param <T> decoded response type
     * @param deliveryId deliveryId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("webhooks|POST|/webhooks/deliveries/{param}/retry")
    public <T> @Nullable T retry(String deliveryId, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Webhooks.POST_WEBHOOKS_DELIVERIES_PARAM_RETRY,
                List.of(deliveryId),
                query,
                body,
                responseType);
    }
    /**
     * Calls the contract route {@code POST /webhooks/deliveries/{param}/retry} using a generic response type.
     * @param <T> decoded response type
     * @param deliveryId deliveryId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T retry(
            String deliveryId, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Webhooks.POST_WEBHOOKS_DELIVERIES_PARAM_RETRY,
                List.of(deliveryId),
                query,
                body,
                responseType);
    }
    /**
     * Calls the contract route {@code POST /webhooks/deliveries/{param}/retry} without query parameters.
     * @param <T> decoded response type
     * @param deliveryId deliveryId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T retry(String deliveryId, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return retry(deliveryId, QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /webhooks/deliveries/{param}/retry} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param deliveryId deliveryId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T retry(String deliveryId, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return retry(deliveryId, QueryParams.empty(), body, responseType);
    }
}
