package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Named contract operations for the webhooks service. Generated by scripts/generate_endpoints.py. */
public final class WebhooksClient extends ServiceClient {
    WebhooksClient(ApiClient client) {
        super(ApiService.WEBHOOKS, client);
    }

    /**
     * Calls the contract route {@code DELETE /webhooks/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("webhooks|DELETE|/webhooks/{param}")
    public <T> @Nullable T deleteWebhooksParam(String pathParam1, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Webhooks.DELETE_WEBHOOKS_PARAM, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code DELETE /webhooks/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T deleteWebhooksParam(String pathParam1, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Webhooks.DELETE_WEBHOOKS_PARAM, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /webhooks}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("webhooks|GET|/webhooks")
    public <T> @Nullable T getWebhooks(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Webhooks.GET_WEBHOOKS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /webhooks}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getWebhooks(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Webhooks.GET_WEBHOOKS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /webhooks/deliveries}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("webhooks|GET|/webhooks/deliveries")
    public <T> @Nullable T getWebhooksDeliveries(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Webhooks.GET_WEBHOOKS_DELIVERIES, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /webhooks/deliveries}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getWebhooksDeliveries(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Webhooks.GET_WEBHOOKS_DELIVERIES, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /webhooks/deliveries/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("webhooks|GET|/webhooks/deliveries/{param}")
    public <T> @Nullable T getWebhooksDeliveriesParam(String pathParam1, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Webhooks.GET_WEBHOOKS_DELIVERIES_PARAM, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /webhooks/deliveries/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getWebhooksDeliveriesParam(
            String pathParam1, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Webhooks.GET_WEBHOOKS_DELIVERIES_PARAM, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /webhooks/stats}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("webhooks|GET|/webhooks/stats")
    public <T> @Nullable T getWebhooksStats(QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Webhooks.GET_WEBHOOKS_STATS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /webhooks/stats}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getWebhooksStats(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Webhooks.GET_WEBHOOKS_STATS, List.of(), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /webhooks/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("webhooks|GET|/webhooks/{param}")
    public <T> @Nullable T getWebhooksParam(String pathParam1, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Webhooks.GET_WEBHOOKS_PARAM, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code GET /webhooks/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T getWebhooksParam(String pathParam1, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Webhooks.GET_WEBHOOKS_PARAM, List.of(pathParam1), query, null, responseType);
    }

    /**
     * Calls the contract route {@code POST /webhooks}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("webhooks|POST|/webhooks")
    public <T> @Nullable T postWebhooks(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Webhooks.POST_WEBHOOKS, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /webhooks}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postWebhooks(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Webhooks.POST_WEBHOOKS, List.of(), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /webhooks/deliveries/{param}/retry}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("webhooks|POST|/webhooks/deliveries/{param}/retry")
    public <T> @Nullable T postWebhooksDeliveriesParamRetry(
            String pathParam1, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Webhooks.POST_WEBHOOKS_DELIVERIES_PARAM_RETRY,
                List.of(pathParam1),
                query,
                body,
                responseType);
    }

    /**
     * Calls the contract route {@code POST /webhooks/deliveries/{param}/retry}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postWebhooksDeliveriesParamRetry(
            String pathParam1, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Webhooks.POST_WEBHOOKS_DELIVERIES_PARAM_RETRY,
                List.of(pathParam1),
                query,
                body,
                responseType);
    }

    /**
     * Calls the contract route {@code POST /webhooks/{param}/rotate-secret}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("webhooks|POST|/webhooks/{param}/rotate-secret")
    public <T> @Nullable T postWebhooksParamRotateSecret(
            String pathParam1, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Webhooks.POST_WEBHOOKS_PARAM_ROTATE_SECRET, List.of(pathParam1), query, body, responseType);
    }

    /**
     * Calls the contract route {@code POST /webhooks/{param}/rotate-secret}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T postWebhooksParamRotateSecret(
            String pathParam1, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Webhooks.POST_WEBHOOKS_PARAM_ROTATE_SECRET, List.of(pathParam1), query, body, responseType);
    }

    /**
     * Calls the contract route {@code PUT /webhooks/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("webhooks|PUT|/webhooks/{param}")
    public <T> @Nullable T putWebhooksParam(
            String pathParam1, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Webhooks.PUT_WEBHOOKS_PARAM, List.of(pathParam1), query, body, responseType);
    }

    /**
     * Calls the contract route {@code PUT /webhooks/{param}}.
     * @param <T> decoded response type
     * @param pathParam1 pathParam1 supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T putWebhooksParam(
            String pathParam1, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Webhooks.PUT_WEBHOOKS_PARAM, List.of(pathParam1), query, body, responseType);
    }
}
