package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for workflows/templates. Generated by scripts/generate_endpoints.py. */
public final class WorkflowsTemplatesClient extends ServiceClient {
    WorkflowsTemplatesClient(ApiClient client) {
        super(ApiService.WORKFLOWS, client);
    }

    /**
     * Calls the contract route {@code GET /workflows/templates}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("workflows|GET|/workflows/templates")
    public <T> @Nullable T list(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.GET_WORKFLOWS_TEMPLATES, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /workflows/templates} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Workflows.GET_WORKFLOWS_TEMPLATES, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /workflows/templates} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(Class<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /workflows/templates} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(TypeReference<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /workflows/templates/{param}}.
     * @param <T> decoded response type
     * @param templateId templateId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("workflows|GET|/workflows/templates/{param}")
    public <T> @Nullable T get(String templateId, QueryParams query, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Workflows.GET_WORKFLOWS_TEMPLATES_PARAM, List.of(templateId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /workflows/templates/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param templateId templateId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String templateId, QueryParams query, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Workflows.GET_WORKFLOWS_TEMPLATES_PARAM, List.of(templateId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /workflows/templates/{param}} without query parameters.
     * @param <T> decoded response type
     * @param templateId templateId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String templateId, Class<T> responseType) throws IOException, InterruptedException {
        return get(templateId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /workflows/templates/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param templateId templateId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String templateId, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return get(templateId, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code POST /workflows/templates}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("workflows|POST|/workflows/templates")
    public <T> @Nullable T create(QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Workflows.POST_WORKFLOWS_TEMPLATES, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /workflows/templates} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(Endpoints.Workflows.POST_WORKFLOWS_TEMPLATES, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /workflows/templates} without query parameters.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(@Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return create(QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /workflows/templates} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(@Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return create(QueryParams.empty(), body, responseType);
    }

    /**
     * Calls the contract route {@code POST /workflows/templates/{param}/instantiate}.
     * @param <T> decoded response type
     * @param templateId templateId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("workflows|POST|/workflows/templates/{param}/instantiate")
    public <T> @Nullable T instantiate(
            String templateId, QueryParams query, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Workflows.POST_WORKFLOWS_TEMPLATES_PARAM_INSTANTIATE,
                List.of(templateId),
                query,
                body,
                responseType);
    }
    /**
     * Calls the contract route {@code POST /workflows/templates/{param}/instantiate} using a generic response type.
     * @param <T> decoded response type
     * @param templateId templateId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T instantiate(
            String templateId, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return request(
                Endpoints.Workflows.POST_WORKFLOWS_TEMPLATES_PARAM_INSTANTIATE,
                List.of(templateId),
                query,
                body,
                responseType);
    }
    /**
     * Calls the contract route {@code POST /workflows/templates/{param}/instantiate} without query parameters.
     * @param <T> decoded response type
     * @param templateId templateId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T instantiate(String templateId, @Nullable JsonNode body, Class<T> responseType)
            throws IOException, InterruptedException {
        return instantiate(templateId, QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /workflows/templates/{param}/instantiate} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param templateId templateId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T instantiate(String templateId, @Nullable JsonNode body, TypeReference<T> responseType)
            throws IOException, InterruptedException {
        return instantiate(templateId, QueryParams.empty(), body, responseType);
    }
}
