package dev.frontal.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.util.List;
import org.jspecify.annotations.Nullable;

/** Contract operations for workflows. Generated by scripts/generate_endpoints.py. */
public class WorkflowsServiceClient extends ServiceClient {
    WorkflowsServiceClient(ApiClient client) {
        super(ApiService.WORKFLOWS, client);
    }

    /** Returns the client for the nested resource.
     * @return the approvals resource client
     */
    public WorkflowsApprovalsClient approvals() {
        return new WorkflowsApprovalsClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the executions resource client
     */
    public WorkflowsExecutionsClient executions() {
        return new WorkflowsExecutionsClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the runs resource client
     */
    public WorkflowsRunsClient runs() {
        return new WorkflowsRunsClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the tasks resource client
     */
    public WorkflowsTasksClient tasks() {
        return new WorkflowsTasksClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the templates resource client
     */
    public WorkflowsTemplatesClient templates() {
        return new WorkflowsTemplatesClient(client());
    }

    /** Returns the client for the nested resource.
     * @return the versions resource client
     */
    public WorkflowsVersionsClient versions() {
        return new WorkflowsVersionsClient(client());
    }

    /**
     * Calls the contract route {@code DELETE /workflows/{param}}.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("workflows|DELETE|/workflows/{param}")
    public <T> @Nullable T delete(String workflowId, QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.DELETE_WORKFLOWS_PARAM, List.of(workflowId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code DELETE /workflows/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T delete(String workflowId, QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.DELETE_WORKFLOWS_PARAM, List.of(workflowId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code DELETE /workflows/{param}} without query parameters.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T delete(String workflowId, Class<T> responseType) throws IOException, InterruptedException {
        return delete(workflowId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code DELETE /workflows/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T delete(String workflowId, TypeReference<T> responseType) throws IOException, InterruptedException {
        return delete(workflowId, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /workflows}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("workflows|GET|/workflows")
    public <T> @Nullable T list(QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.GET_WORKFLOWS, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /workflows} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.GET_WORKFLOWS, List.of(), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /workflows} without query parameters.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(Class<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /workflows} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T list(TypeReference<T> responseType) throws IOException, InterruptedException {
        return list(QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /workflows/{param}}.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("workflows|GET|/workflows/{param}")
    public <T> @Nullable T get(String workflowId, QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.GET_WORKFLOWS_PARAM, List.of(workflowId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /workflows/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String workflowId, QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.GET_WORKFLOWS_PARAM, List.of(workflowId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /workflows/{param}} without query parameters.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String workflowId, Class<T> responseType) throws IOException, InterruptedException {
        return get(workflowId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /workflows/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get(String workflowId, TypeReference<T> responseType) throws IOException, InterruptedException {
        return get(workflowId, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /workflows/{param}/{param}}.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param runId runId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("workflows|GET|/workflows/{param}/{param}")
    public <T> @Nullable T get2(String workflowId, String runId, QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.GET_WORKFLOWS_PARAM_PARAM, List.of(workflowId, runId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /workflows/{param}/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param runId runId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get2(String workflowId, String runId, QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.GET_WORKFLOWS_PARAM_PARAM, List.of(workflowId, runId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /workflows/{param}/{param}} without query parameters.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param runId runId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get2(String workflowId, String runId, Class<T> responseType) throws IOException, InterruptedException {
        return get2(workflowId, runId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /workflows/{param}/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param runId runId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T get2(String workflowId, String runId, TypeReference<T> responseType) throws IOException, InterruptedException {
        return get2(workflowId, runId, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /workflows/{param}/{param}/summary}.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param runId runId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("workflows|GET|/workflows/{param}/{param}/summary")
    public <T> @Nullable T summary(String workflowId, String runId, QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.GET_WORKFLOWS_PARAM_PARAM_SUMMARY, List.of(workflowId, runId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /workflows/{param}/{param}/summary} using a generic response type.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param runId runId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T summary(String workflowId, String runId, QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.GET_WORKFLOWS_PARAM_PARAM_SUMMARY, List.of(workflowId, runId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /workflows/{param}/{param}/summary} without query parameters.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param runId runId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T summary(String workflowId, String runId, Class<T> responseType) throws IOException, InterruptedException {
        return summary(workflowId, runId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /workflows/{param}/{param}/summary} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param runId runId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T summary(String workflowId, String runId, TypeReference<T> responseType) throws IOException, InterruptedException {
        return summary(workflowId, runId, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code GET /workflows/{param}/{param}/timeline}.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param runId runId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("workflows|GET|/workflows/{param}/{param}/timeline")
    public <T> @Nullable T timeline(String workflowId, String runId, QueryParams query, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.GET_WORKFLOWS_PARAM_PARAM_TIMELINE, List.of(workflowId, runId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /workflows/{param}/{param}/timeline} using a generic response type.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param runId runId supplied to the operation
     * @param query query supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T timeline(String workflowId, String runId, QueryParams query, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.GET_WORKFLOWS_PARAM_PARAM_TIMELINE, List.of(workflowId, runId), query, null, responseType);
    }
    /**
     * Calls the contract route {@code GET /workflows/{param}/{param}/timeline} without query parameters.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param runId runId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T timeline(String workflowId, String runId, Class<T> responseType) throws IOException, InterruptedException {
        return timeline(workflowId, runId, QueryParams.empty(), responseType);
    }
    /**
     * Calls the contract route {@code GET /workflows/{param}/{param}/timeline} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param runId runId supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T timeline(String workflowId, String runId, TypeReference<T> responseType) throws IOException, InterruptedException {
        return timeline(workflowId, runId, QueryParams.empty(), responseType);
    }

    /**
     * Calls the contract route {@code PATCH /workflows/{param}}.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("workflows|PATCH|/workflows/{param}")
    public <T> @Nullable T update(String workflowId, QueryParams query, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.PATCH_WORKFLOWS_PARAM, List.of(workflowId), query, body, responseType);
    }
    /**
     * Calls the contract route {@code PATCH /workflows/{param}} using a generic response type.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T update(String workflowId, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.PATCH_WORKFLOWS_PARAM, List.of(workflowId), query, body, responseType);
    }
    /**
     * Calls the contract route {@code PATCH /workflows/{param}} without query parameters.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T update(String workflowId, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return update(workflowId, QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code PATCH /workflows/{param}} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T update(String workflowId, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return update(workflowId, QueryParams.empty(), body, responseType);
    }

    /**
     * Calls the contract route {@code POST /workflows}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("workflows|POST|/workflows")
    public <T> @Nullable T create(QueryParams query, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.POST_WORKFLOWS, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /workflows} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.POST_WORKFLOWS, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /workflows} without query parameters.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(@Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return create(QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /workflows} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T create(@Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return create(QueryParams.empty(), body, responseType);
    }

    /**
     * Calls the contract route {@code POST /workflows/batch}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("workflows|POST|/workflows/batch")
    public <T> @Nullable T batch(QueryParams query, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.POST_WORKFLOWS_BATCH, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /workflows/batch} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T batch(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.POST_WORKFLOWS_BATCH, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /workflows/batch} without query parameters.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T batch(@Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return batch(QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /workflows/batch} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T batch(@Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return batch(QueryParams.empty(), body, responseType);
    }

    /**
     * Calls the contract route {@code POST /workflows/search}.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("workflows|POST|/workflows/search")
    public <T> @Nullable T search(QueryParams query, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.POST_WORKFLOWS_SEARCH, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /workflows/search} using a generic response type.
     * @param <T> decoded response type
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T search(QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.POST_WORKFLOWS_SEARCH, List.of(), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /workflows/search} without query parameters.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T search(@Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return search(QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /workflows/search} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T search(@Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return search(QueryParams.empty(), body, responseType);
    }

    /**
     * Calls the contract route {@code POST /workflows/{param}/archive}.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("workflows|POST|/workflows/{param}/archive")
    public <T> @Nullable T archive(String workflowId, QueryParams query, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.POST_WORKFLOWS_PARAM_ARCHIVE, List.of(workflowId), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /workflows/{param}/archive} using a generic response type.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T archive(String workflowId, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.POST_WORKFLOWS_PARAM_ARCHIVE, List.of(workflowId), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /workflows/{param}/archive} without query parameters.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T archive(String workflowId, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return archive(workflowId, QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /workflows/{param}/archive} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T archive(String workflowId, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return archive(workflowId, QueryParams.empty(), body, responseType);
    }

    /**
     * Calls the contract route {@code POST /workflows/{param}/publish}.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("workflows|POST|/workflows/{param}/publish")
    public <T> @Nullable T publish(String workflowId, QueryParams query, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.POST_WORKFLOWS_PARAM_PUBLISH, List.of(workflowId), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /workflows/{param}/publish} using a generic response type.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T publish(String workflowId, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.POST_WORKFLOWS_PARAM_PUBLISH, List.of(workflowId), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /workflows/{param}/publish} without query parameters.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T publish(String workflowId, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return publish(workflowId, QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /workflows/{param}/publish} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T publish(String workflowId, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return publish(workflowId, QueryParams.empty(), body, responseType);
    }

    /**
     * Calls the contract route {@code POST /workflows/{param}/restore}.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    @SdkOperation("workflows|POST|/workflows/{param}/restore")
    public <T> @Nullable T restore(String workflowId, QueryParams query, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.POST_WORKFLOWS_PARAM_RESTORE, List.of(workflowId), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /workflows/{param}/restore} using a generic response type.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param query query supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T restore(String workflowId, QueryParams query, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return request(Endpoints.Workflows.POST_WORKFLOWS_PARAM_RESTORE, List.of(workflowId), query, body, responseType);
    }
    /**
     * Calls the contract route {@code POST /workflows/{param}/restore} without query parameters.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T restore(String workflowId, @Nullable JsonNode body, Class<T> responseType) throws IOException, InterruptedException {
        return restore(workflowId, QueryParams.empty(), body, responseType);
    }
    /**
     * Calls the contract route {@code POST /workflows/{param}/restore} without query parameters using a generic response type.
     * @param <T> decoded response type
     * @param workflowId workflowId supplied to the operation
     * @param body body supplied to the operation
     * @param responseType responseType supplied to the operation
     * @return the decoded response, or null when the response body is empty
     * @throws IOException if the operation fails
     * @throws InterruptedException if the operation fails
     */
    public <T> @Nullable T restore(String workflowId, @Nullable JsonNode body, TypeReference<T> responseType) throws IOException, InterruptedException {
        return restore(workflowId, QueryParams.empty(), body, responseType);
    }

}
