#!/usr/bin/env python3
"""Generate Java endpoint constants from the shared SDK route inventory."""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT / "contracts/sdk-endpoints.json"
OUTPUT = ROOT / "src/main/java/dev/frontal/sdk/resources/Endpoints.java"
CONFORMANCE = ROOT / "contracts/reports/conformance.json"
MIGRATION_MATRIX = ROOT / "contracts/reports/migration-matrix.md"
SERVICES = {
    "agents": "AGENTS",
    "ai": "AI",
    "audit": "AUDIT",
    "auth": "AUTH",
    "billing": "BILLING",
    "blob": "BLOB",
    "connectors": "CONNECTORS",
    "data": "DATA",
    "governance": "GOVERNANCE",
    "lineage": "LINEAGE",
    "observability": "OBSERVABILITY",
    "ontology": "ONTOLOGY",
    "pipelines": "PIPELINES",
    "react": "REACT",
    "sandbox": "SANDBOX",
    "schedules": "SCHEDULES",
    "webhooks": "WEBHOOKS",
    "workflows": "WORKFLOWS",
}


def constant_name(method: str, path: str) -> str:
    route = path.replace("{param}", "PARAM")
    parts = re.findall(r"[A-Za-z0-9]+", route)
    return "_".join([method, *parts]).upper()


def main() -> None:
    routes = json.loads(CONTRACT.read_text(encoding="utf-8"))
    missing = set(SERVICES) - routes.keys()
    if missing:
        raise SystemExit(f"Missing service contracts: {sorted(missing)}")
    lines = [
        "package dev.frontal.sdk;",
        "",
        "/** Contract-backed routes grouped by API service. Generated by scripts/generate_endpoints.py. */",
        "public final class Endpoints {",
        "  private Endpoints() {}",
    ]
    for service, enum_value in SERVICES.items():
        lines.extend(
            [
                "",
                f"  public static final class {enum_value.title()} {{",
                f"    private {enum_value.title()}() {{}}",
            ]
        )
        if routes[service]:
            lines.append("")
        used: dict[str, int] = {}
        for route in sorted(routes[service], key=lambda item: (item["method"], item["path"])):
            name = constant_name(route["method"], route["path"])
            count = used.get(name, 0)
            used[name] = count + 1
            if count:
                name = f"{name}_{count + 1}"
            declaration = (
                f'        new Endpoint(ApiService.{enum_value}, '
                f'HttpMethod.{route["method"]}, "{route["path"]}");'
            )
            lines.append(f"    public static final Endpoint {name} =")
            arguments = (
                f'ApiService.{enum_value}, HttpMethod.{route["method"]}, '
                f'"{route["path"]}"'
            )
            if len(declaration) <= 100:
                lines.append(declaration)
            elif len(arguments) + 14 <= 100:
                lines.extend(["        new Endpoint(", f"            {arguments});"])
            else:
                lines.extend(
                    [
                        "        new Endpoint(",
                        f"            ApiService.{enum_value},",
                        f"            HttpMethod.{route['method']},",
                        f'            "{route["path"]}");',
                    ]
                )
        lines.append("  }")
    lines.append("}")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    endpoint_count = sum(len(service_routes) for service_routes in routes.values())
    report = {
        "repository": "sdk-java",
        "language": "Java",
        "status": "route-catalogued",
        "contractEndpointEntries": endpoint_count,
        "generatedEndpointConstants": endpoint_count,
        "catalogCoverage": "100%",
        "note": (
            "All routes in sdk-endpoints.json have generated endpoint constants and share the "
            "generic SDK transport. Route-specific typed models are not generated because the "
            "inventory does not provide complete schemas."
        ),
    }
    CONFORMANCE.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    MIGRATION_MATRIX.write_text(
        "# Java SDK route coverage\n\n"
        "_Status: generated route catalog complete. This measures catalog coverage and generic "
        "transport availability, not route-specific typed models._\n\n"
        "| Metric | Value |\n| --- | ---: |\n"
        f"| Contract endpoint entries | {endpoint_count} |\n"
        f"| Generated endpoint constants | {endpoint_count} |\n"
        "| Catalog coverage | 100% |\n"
        "| Route-specific typed request/response models | Not generated |\n\n"
        "`scripts/generate_endpoints.py` regenerates "
        "`src/main/java/dev/frontal/sdk/resources/Endpoints.java` from "
        "`contracts/sdk-endpoints.json`. All catalogued routes use the shared Java transport; "
        "callers provide response types when decoding JSON.\n",
        encoding="utf-8",
    )
    print(f"Generated {endpoint_count} endpoint constants across {len(routes)} services.")


if __name__ == "__main__":
    main()
